(function(){
'use strict';
const $=id=>document.getElementById(id), state={settings:null,catalogue:[],wears:[],weather:null,current:null,lastIds:[]};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number(String(v??'').replace(/[^0-9.-]/g,''))||0;
const norm=v=>String(v||'').trim().toLowerCase();
const split=v=>String(v||'').split(/[,/|;]+/).map(x=>norm(x)).filter(Boolean);
const endpoint=action=>state.settings.adminWriteEndpoint+(state.settings.adminWriteEndpoint.includes('?')?'&':'?')+'action='+encodeURIComponent(action)+'&t='+Date.now();
async function get(action){const r=await fetch(endpoint(action),{cache:'no-store'});if(!r.ok)throw new Error(action+' failed');const j=await r.json();if(j.ok===false)throw new Error(j.error||action+' failed');return j;}
function seasonFor(date=new Date()){const m=date.getMonth()+1;return m===12||m<=2?'Summer':m<=5?'Autumn':m<=8?'Winter':'Spring';}
function available(i){const stock=norm(i.Stock),ml=num(i['Current mL']);return !/out of stock|sold out/.test(stock)&&(ml>0||!String(i['Current mL']||'').trim());}
function ageDays(v){if(!v)return 9999;const d=new Date(v);return Number.isNaN(d)?9999:Math.floor((Date.now()-d.getTime())/86400000);}
function lastWearMap(){const m=new Map();state.wears.forEach(w=>{const id=String(w['Fragrance ID']||'');const d=new Date(w.Date||w.Timestamp||0);if(id&&(!m.has(id)||d>m.get(id)))m.set(id,d)});return m;}
function dayOccasion(type){const t=norm(type);if(t.includes('office'))return ['daily','versatile','office'];if(t.includes('home'))return ['daily','versatile'];if(t.includes('date'))return ['date','night'];if(t.includes('going'))return ['date','night','versatile'];if(t.includes('sport'))return ['daily','summer','fresh'];return ['daily','versatile'];}
function moodStyles(mood){const m=norm(mood);if(m.includes('fresh'))return ['fresh aquatic','fresh citrus'];if(m.includes('warm'))return ['vanilla','gourmand','tobacco','woody','spicy'];if(m.includes('dark'))return ['dark / night','leather','tobacco','spicy'];if(m.includes('sweet'))return ['vanilla','gourmand','fruity'];return [];}
function weatherStyles(temp,condition){const c=norm(condition);if(temp>=27)return ['fresh aquatic','fresh citrus','fruity','floral'];if(temp<=14)return ['vanilla','gourmand','tobacco','woody','spicy','dark / night','leather'];if(c.includes('rain')||c.includes('cloud'))return ['woody','spicy','vanilla','fresh aquatic'];return ['fresh citrus','fresh aquatic','woody','fruity','floral'];}
function score(i){let s=15,reasons=[];const season=seasonFor(),seasons=split(i.Season),style=norm(i['Scent Style']),occasion=split(i.Occasion),temp=num($('temperature').value),cond=$('condition').value,type=$('dayType').value,mood=$('mood').value;
 if(seasons.includes(norm(season))||seasons.includes('all year')){s+=34;reasons.push(`${season} fit`);}else if(seasons.length){s-=12;}
 const occ=dayOccasion(type);if(occasion.some(x=>occ.some(o=>x.includes(o)))){s+=22;reasons.push(type==='Work from home'?'easy daily wear':type.toLowerCase()+' friendly');}
 const ws=weatherStyles(temp,cond);if(ws.includes(style)){s+=18;reasons.push(`${i['Scent Style']} suits ${temp?Math.round(temp)+'°C ':''}${cond||'today'}`);}
 const ms=moodStyles(mood);if(ms.length&&ms.includes(style)){s+=15;reasons.push('matches your mood');}
 const lw=lastWearMap().get(String(i.ID));const days=lw?Math.floor((Date.now()-lw.getTime())/86400000):9999;if(days>45){s+=12;reasons.push('hasn’t been worn recently');}else if(days<7)s-=18;
 if(state.lastIds.includes(String(i.ID)))s-=20;const ml=num(i['Current mL']);if(ml>0&&ml<12)s-=4;
 return {item:i,score:s,reasons:reasons.slice(0,3),days};}
function weightedPick(pool){const min=Math.min(...pool.map(x=>x.score)),weighted=pool.map(x=>({...x,w:Math.max(1,x.score-min+8)}));let total=weighted.reduce((a,x)=>a+x.w,0),r=Math.random()*total;for(const x of weighted){r-=x.w;if(r<=0)return x;}return weighted[0];}
function pick(){let ranked=state.catalogue.filter(available).map(score).sort((a,b)=>b.score-a.score);if(!ranked.length)return;const shortlist=ranked.slice(0,Math.min(14,ranked.length));const chosen=weightedPick(shortlist),alts=ranked.filter(x=>x.item.ID!==chosen.item.ID).slice(0,6);state.current=chosen;state.lastIds=[String(chosen.item.ID),...state.lastIds].slice(0,5);renderPick(chosen,alts);}
function renderPick(p,alts){const i=p.item;$('pickPanel').hidden=false;$('mainPick').innerHTML=`<article class="daily-hero-pick">${i.Image?`<img src="${esc(i.Image)}" alt="">`:''}<div><span class="daily-style">${esc(i['Scent Style']||'Today’s fragrance')}</span><h2>${esc(i.House)} · ${esc(i.Fragrance)}</h2><p>${esc(i.Description||'')}</p><div class="daily-reasons">${p.reasons.map(r=>`<span>✓ ${esc(r)}</span>`).join('')}</div><small>${esc(i.Season||'All year')} · ${esc(i.Occasion||'Versatile')}</small></div></article>`;
 $('alternatives').innerHTML=alts.slice(0,3).map(x=>`<button type="button" class="daily-alt" data-id="${esc(x.item.ID)}"><strong>${esc(x.item.House)} · ${esc(x.item.Fragrance)}</strong><span>${esc(x.item['Scent Style']||'')} · ${esc(x.reasons[0]||'Good fit today')}</span></button>`).join('');$('pickPanel').scrollIntoView({behavior:'smooth',block:'start'});}
async function weather(){try{const j=await get('dailyPickWeather');if(j.weather){state.weather=j.weather;$('temperature').value=Math.round(j.weather.tempC);$('condition').value=[...$('condition').options].find(o=>norm(j.weather.condition).includes(norm(o.value))||norm(o.value).includes(norm(j.weather.condition)))?.value||'';$('weatherCard').innerHTML=`<strong>${esc(j.weather.location)} · ${Math.round(j.weather.tempC)}°C</strong><span>${esc(j.weather.condition)} · feels like ${Math.round(j.weather.feelsC)}°C · ${esc(seasonFor())}</span><small>WeatherAPI.com · updated ${esc(j.weather.updated||'now')}</small>`;return;}}catch(e){}$('weatherCard').innerHTML=`<strong>${esc(seasonFor())} · Manual weather mode</strong><span>Enter today's temperature and conditions below. Add the free WeatherAPI key later for automatic Sydney weather.</span>`;}
async function wear(){if(!state.current)return;const i=state.current.item,payload={action:'logWear',wear:{date:new Date().toISOString(),fragranceId:i.ID,house:i.House,fragrance:i.Fragrance,scentStyle:i['Scent Style']||'',season:seasonFor(),dayType:$('dayType').value,tempC:num($('temperature').value),condition:$('condition').value,mood:$('mood').value,source:'Daily Pick'}};$('wearButton').disabled=true;try{await DeadEndAdminWrite.submit(state.settings.adminWriteEndpoint,payload,{timeout:45000});$('dailyStatus').textContent=`Logged: ${i.House} · ${i.Fragrance} is today's wear.`;await loadWears();renderWearIntel();}catch(e){$('dailyStatus').textContent='Could not log wear: '+(e.message||e);}finally{$('wearButton').disabled=false;}}
async function loadWears(){try{const j=await get('wearLog');state.wears=j.items||[];}catch(e){state.wears=[];}}
function renderWearIntel(){const wears=state.wears,now=new Date(),month=wears.filter(w=>{const d=new Date(w.Date||w.Timestamp);return !Number.isNaN(d)&&d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()});const counts={};wears.forEach(w=>{const n=[w.House,w.Fragrance].filter(Boolean).join(' · ');counts[n]=(counts[n]||0)+1});const top=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];const last=lastWearMap(),neg=state.catalogue.filter(available).map(i=>({i,days:last.has(String(i.ID))?Math.floor((Date.now()-last.get(String(i.ID)).getTime())/86400000):9999})).sort((a,b)=>b.days-a.days);$('wearCount').textContent=wears.length;$('wearMonth').textContent=month.length;$('mostWorn').textContent=top?top[0].split(' · ').pop():'—';$('neglectedCount').textContent=neg.filter(x=>x.days>90).length;$('recentWears').innerHTML=wears.slice(0,8).map(w=>`<div class="mini-row"><div><strong>${esc(w.House)} · ${esc(w.Fragrance)}</strong><span>${esc(w['Day Type']||'')} · ${esc(w.Condition||'')} ${w['Temp C']?w['Temp C']+'°C':''}</span></div><em>${esc(new Date(w.Date||w.Timestamp).toLocaleDateString('en-AU'))}</em></div>`).join('')||'<div class="empty">No wears logged yet.</div>';$('neglected').innerHTML=neg.slice(0,6).map(x=>`<button class="mini-row neglected-pick" data-id="${esc(x.i.ID)}"><div><strong>${esc(x.i.House)} · ${esc(x.i.Fragrance)}</strong><span>${x.days>9000?'Never logged':x.days+' days since last wear'} · ${esc(x.i['Scent Style']||'')}</span></div><em>Pick</em></button>`).join('');}
async function load(){state.settings=await fetch('../settings.json',{cache:'no-store'}).then(r=>r.json());const cat=await get('catalogue');state.catalogue=cat.items||[];await Promise.all([loadWears(),weather()]);renderWearIntel();$('dailyStatus').textContent=`Ready · ${state.catalogue.filter(available).length} available fragrances · ${seasonFor()} in Sydney`;}
$('pickButton').onclick=pick;$('surpriseButton').onclick=()=>{$('mood').value='Something different';$('dayType').value='Surprise me';pick();};$('rerollButton').onclick=pick;$('wearButton').onclick=wear;$('refreshWeather').onclick=weather;$('alternatives').onclick=e=>{const b=e.target.closest('[data-id]');if(!b)return;const x=score(state.catalogue.find(i=>String(i.ID)===b.dataset.id));state.current=x;renderPick(x,[]);};$('neglected').onclick=e=>{const b=e.target.closest('[data-id]');if(!b)return;const x=score(state.catalogue.find(i=>String(i.ID)===b.dataset.id));state.current=x;renderPick(x,[]);};
load().catch(e=>$('dailyStatus').textContent='Could not load Daily Pick: '+(e.message||e));
})();
