// DeadEnd Scents catalogue data. Update this file when your fragrance list changes.
window.siteConfig = {
  "facebookMessengerUrl": "https://m.me/YOUR_FACEBOOK_PAGE",
  "whatsAppUrl": "https://wa.me/61YOURNUMBER?text=Hi%20DeadEnd%20Scents%2C%20I%27d%20like%20to%20order%20some%20samples.",
  "instagramUrl": "https://instagram.com/YOUR_INSTAGRAM",
  "businessName": "DeadEnd Scents"
};

const fragrances = [
  {
    "name": "Supremacy Collectors Ed.",
    "house": "Afnan",
    "inspiration": "Creed - Absolu Aventus",
    "status": "In stock",
    "emojis": "🍍🪵🌫",
    "p3": "$6",
    "p5": "$11",
    "p10": "$14",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Afnan/Supremacy-Collector-s-Edition-Pour-Homme-98689.html",
    "category": "Fruity Woods",
    "occasion": "Daily / Versatile",
    "notes": "pineapple, citrus, smoky woods"
  },
  {
    "name": "Supremacy in Heaven",
    "house": "Afnan",
    "inspiration": "Creed - Silver Mountain Water",
    "status": "In stock",
    "emojis": "🍊🌿🪵",
    "p3": "$5",
    "p5": "$9",
    "p10": "$13",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Afnan/Supremacy-In-Heaven-70703.html",
    "category": "Fresh / Clean",
    "occasion": "Daily / Summer",
    "notes": "citrus, green tea, clean musk"
  },
  {
    "name": "9PM - Night Out Extrait",
    "house": "Afnan",
    "inspiration": "Original Creation",
    "status": "In stock",
    "emojis": "🍏🥃🧥",
    "p3": "$6",
    "p5": "$9",
    "p10": "$13",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Afnan/9-PM-Night-Out-123313.html",
    "imageUrl": "https://fimgs.net/mdimg/perfume/375x500.123313.jpg",
    "category": "Fruity / Night Out",
    "occasion": "Date / Autumn",
    "notes": "dragon fruit, apple, cognac, toffee, suede, tonka"
  },
  {
    "name": "Kaaf Extrait",
    "house": "Ahmed Al Maghrabi",
    "inspiration": "Parfums de Marly - Percival",
    "status": "In stock",
    "emojis": "🍋🧼🌿",
    "p3": "$4",
    "p5": "$7",
    "p10": "$12",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Ahmed-Al-Maghribi/Kaaf-102460.html",
    "category": "Fresh / Clean",
    "occasion": "Daily / Summer",
    "notes": "citrus, lavender, clean musk"
  },
  {
    "name": "Aqua Oud",
    "house": "Ahmed Al Maghrabi",
    "inspiration": "Armani - Acqua di Giò Profumo",
    "status": "In stock",
    "emojis": "🌊🪵🕌",
    "p3": "$5",
    "p5": "$8",
    "p10": "$12",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Ahmed-Al-Maghribi/Aqua-Oud-111001.html",
    "category": "Aquatic",
    "occasion": "Daily / Summer",
    "notes": "marine notes, citrus, woods"
  },
  {
    "name": "Ignite Oud Extrait",
    "house": "Ahmed Al Maghrabi",
    "inspiration": "Original Creation",
    "status": "In stock",
    "emojis": "🔥🧥🌲",
    "p3": "$9",
    "p5": "$15",
    "p10": "$28",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Ahmed-Al-Maghribi/Ignite-Oud-99960.html",
    "imageUrl": "https://fimgs.net/mdimg/perfume/375x500.99960.jpg",
    "category": "Woody Leather",
    "occasion": "Date / Autumn",
    "notes": "leather, patchouli, cedar, amber"
  },
  {
    "name": "Club de Nuit Precieux I",
    "house": "ARMAF",
    "inspiration": "Creed - Absolu Aventus",
    "status": "In stock",
    "emojis": "🪵🍍🌫",
    "p3": "$6",
    "p5": "$11",
    "p10": "$14",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=ARMAF%20Club%20de%20Nuit%20Precieux%20I",
    "category": "Fruity Woods",
    "occasion": "Daily / Versatile",
    "notes": "pineapple, citrus, smoky woods"
  },
  {
    "name": "Club de Nuit Intense Man EDT",
    "house": "ARMAF",
    "inspiration": "Creed - Aventus",
    "status": "In stock",
    "emojis": "🍍🌲🔥",
    "p3": "$5",
    "p5": "$8",
    "p10": "$13",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Armaf/Club-de-Nuit-Intense-Man-34696.html",
    "imageUrl": "https://fimgs.net/mdimg/perfume/375x500.34696.jpg",
    "category": "Fruity Woods",
    "occasion": "Daily / Versatile",
    "notes": "pineapple, citrus, smoky woods"
  },
  {
    "name": "Wild Colt",
    "house": "Assaf",
    "inspiration": "Gissah - Imperial Valley",
    "status": "In stock",
    "emojis": "🐎🧥🍋",
    "p3": "$6",
    "p5": "$11",
    "p10": "$18",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Assaf/Wild-Colt-75834.html",
    "imageUrl": "https://fimgs.net/mdimg/perfume/375x500.75834.jpg",
    "category": "Leather / Woody",
    "occasion": "Date / Autumn",
    "notes": "saffron, grapefruit, leather, patchouli, ambergris"
  },
  {
    "name": "Boss Life Extrait",
    "house": "Bujairami",
    "inspiration": "Amouage - Outlands",
    "status": "In stock",
    "emojis": "🌙🔥🌿",
    "p3": "$5",
    "p5": "$8",
    "p10": "$12",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Bujairami/Boss-Life-Extreme-123008.html",
    "category": "Amber / Aromatic",
    "occasion": "Date / Autumn",
    "notes": "warm spice, amber, aromatic woods"
  },
  {
    "name": "Kingsman Extrait",
    "house": "Bujairami",
    "inspiration": "Creed - Aventus",
    "status": "In stock",
    "emojis": "🍍🪵👑",
    "p3": "$5",
    "p5": "$8",
    "p10": "$12",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Bujairami/Kingsman-133329.html",
    "category": "Fruity Woods",
    "occasion": "Daily / Versatile",
    "notes": "pineapple, citrus, smoky woods"
  },
  {
    "name": "Gladiator",
    "house": "Bujairami",
    "inspiration": "Argos - Triumph of Bacchus",
    "status": "In stock",
    "emojis": "🍎🥃🏛",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Bujairami/Gladiator-134754.html",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Emperor",
    "house": "Bujairami",
    "inspiration": "Creed - Absolu Aventus",
    "status": "In stock",
    "emojis": "🍍🪵🔥",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bujairami%20Emperor",
    "category": "Fruity Woods",
    "occasion": "Daily / Versatile",
    "notes": "pineapple, citrus, smoky woods"
  },
  {
    "name": "Aqua Pure",
    "house": "Bujairami",
    "inspiration": "Armani - Acqua di Giò Absolu",
    "status": "In stock",
    "emojis": "🌊🍊🪵",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bujairami%20Aqua%20Pure",
    "category": "Aquatic",
    "occasion": "Daily / Summer",
    "notes": "marine notes, citrus, woods"
  },
  {
    "name": "The Rock Intensely",
    "house": "Bujairami",
    "inspiration": "Armani - SWY Intensely",
    "status": "In stock",
    "emojis": "🔥🍦🌰",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Bujairami/The-Rock-Intensely-123810.html",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Gotham",
    "house": "Bujairami",
    "inspiration": "Bond No.9 - Bleecker St.",
    "status": "In stock",
    "emojis": "🦇🌃🔥",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Bond-No-9/Bleecker-Street-1301.html",
    "category": "Green Fruity",
    "occasion": "Daily / Summer",
    "notes": "blueberry, violet leaf, woods"
  },
  {
    "name": "Ocean Drip",
    "house": "Bujairami",
    "inspiration": "Bvlgari - Aqva Pour Homme Atlantiqve",
    "status": "In stock",
    "emojis": "🌊🌀❄",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bujairami%20Ocean%20Drip",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Mafia Boss Extrait",
    "house": "Bujairami",
    "inspiration": "Clive Christian - Blonde Amber",
    "status": "In stock",
    "emojis": "🍦🥃🕴",
    "p3": "$5",
    "p5": "$8",
    "p10": "$12",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Bujairami/Mafia-Boss-117832.html",
    "category": "Amber / Boozy",
    "occasion": "Date / Autumn",
    "notes": "amber, vanilla, booze, woods"
  },
  {
    "name": "High Tide Mojito",
    "house": "Bujairami",
    "inspiration": "Clive Christian - Crab Apple Blossom",
    "status": "In stock",
    "emojis": "🌊🍃🍏",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bujairami%20High%20Tide%20Mojito",
    "category": "Fresh Fruity",
    "occasion": "Daily / Summer",
    "notes": "apple, marine notes, mint"
  },
  {
    "name": "Bossman Extrait",
    "house": "Bujairami",
    "inspiration": "Creed - Absolu Aventus (2025)",
    "status": "In stock",
    "emojis": "💼🍍🔥",
    "p3": "$5",
    "p5": "$8",
    "p10": "$12",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Bujairami/Bossman-124707.html",
    "category": "Fruity Woods",
    "occasion": "Daily / Versatile",
    "notes": "pineapple, citrus, smoky woods"
  },
  {
    "name": "Finesse (W)",
    "house": "Bujairami",
    "inspiration": "Dior - Blooming Bouquet",
    "status": "In stock",
    "emojis": "🌸🍑🎀",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bujairami%20Finesse%20%28W%29",
    "category": "Floral",
    "occasion": "Daily / Feminine",
    "notes": "peony, rose, peach"
  },
  {
    "name": "Romantic Rose (W)",
    "house": "Bujairami",
    "inspiration": "Initio Parfums Prives - Atomic Rose",
    "status": "In stock",
    "emojis": "🌹💥🔥",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bujairami%20Romantic%20Rose%20%28W%29",
    "category": "Rose Amber",
    "occasion": "Date / Autumn",
    "notes": "rose, vanilla, amber"
  },
  {
    "name": "Booz Extreme",
    "house": "Bujairami",
    "inspiration": "By Kilian - Angels Share",
    "status": "In stock",
    "emojis": "🥃🔥🪵",
    "p3": "$5",
    "p5": "$7",
    "p10": "$11",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bujairami%20Booz%20Extreme",
    "category": "Boozy Sweet",
    "occasion": "Date / Autumn",
    "notes": "cognac, spice, oak, vanilla warmth"
  },
  {
    "name": "Shu Helou",
    "house": "Bujairami",
    "inspiration": "Chanel - Bleu de Chanel EDP",
    "status": "In stock",
    "emojis": "🍋🌿🪵",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bujairami%20Shu%20Helou",
    "category": "Blue / Woody",
    "occasion": "Daily / Summer",
    "notes": "citrus, woods, amber, incense"
  },
  {
    "name": "Iris Infinite Extrait",
    "house": "Bujairami",
    "inspiration": "Dior - Homme Parfum 2025",
    "status": "In stock",
    "emojis": "🪻🪾🧥",
    "p3": "$5",
    "p5": "$8",
    "p10": "$12",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bujairami%20Iris%20Infinite%20Extrait",
    "category": "Iris / Leather",
    "occasion": "Date / Autumn",
    "notes": "iris, amber, woods, leather nuance"
  },
  {
    "name": "Midnight Booz",
    "house": "Bujairami",
    "inspiration": "By Kilian - Angels Share Paradis",
    "status": "In stock",
    "emojis": "🍇🛋🥃",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bujairami%20Midnight%20Booz",
    "category": "Boozy Sweet",
    "occasion": "Date / Autumn",
    "notes": "cognac, spice, oak, vanilla warmth"
  },
  {
    "name": "High Roller",
    "house": "Bujairami",
    "inspiration": "Valentino - Born in Roma Extradose",
    "status": "In stock",
    "emojis": "🎲🍦🌿",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bujairami%20High%20Roller",
    "category": "Fruity Sweet",
    "occasion": "Date / Autumn",
    "notes": "apple, woods, amber sweetness"
  },
  {
    "name": "Booz",
    "house": "Bujairami",
    "inspiration": "By Kilian - Angels Share Twist",
    "status": "In stock",
    "emojis": "🥃🍏🔥",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Bujairami/Booz-124583.html",
    "category": "Boozy Sweet",
    "occasion": "Date / Autumn",
    "notes": "cognac, spice, oak, vanilla warmth"
  },
  {
    "name": "Boujee (W)",
    "house": "Bujairami",
    "inspiration": "Louis Vuitton - Attrape-Rêves",
    "status": "In stock",
    "emojis": "🌸🍫✨",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bujairami%20Boujee%20%28W%29",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Riverina Extrait",
    "house": "Bujairami",
    "inspiration": "Original Creation",
    "status": "In stock",
    "emojis": "🌿💧🍊",
    "p3": "$6",
    "p5": "$9",
    "p10": "$15",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bujairami%20Riverina%20Extrait",
    "category": "Fresh / Citrus",
    "occasion": "Daily / Summer",
    "notes": "citrus, green notes, watery freshness"
  },
  {
    "name": "Lucky",
    "house": "Bujairami",
    "inspiration": "Paco Rabanne - 1M Lucky",
    "status": "In stock",
    "emojis": "🌰🍯💰",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bujairami%20Lucky",
    "category": "Sweet / Nutty",
    "occasion": "Date / Autumn",
    "notes": "hazelnut, honey, plum"
  },
  {
    "name": "Untouchable",
    "house": "Bujairami",
    "inspiration": "Paco Rabanne - Invictus Parfum",
    "status": "In stock",
    "emojis": "🛡🌊🏆",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bujairami%20Untouchable",
    "category": "Fresh Amber",
    "occasion": "Daily / Summer",
    "notes": "aquatic freshness, amber woods"
  },
  {
    "name": "Wicked",
    "house": "Bujairami",
    "inspiration": "Parfums de Marly - Greenley",
    "status": "In stock",
    "emojis": "🍏🌿💨",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bujairami%20Wicked",
    "category": "Green Fruity",
    "occasion": "Daily / Summer",
    "notes": "green apple, woods, musk"
  },
  {
    "name": "Smoldering Sir",
    "house": "Bujairami",
    "inspiration": "Penhaligons - Blazing Mr. Sam",
    "status": "In stock",
    "emojis": "🥃🧴🛋",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bujairami%20Smoldering%20Sir",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "ICE",
    "house": "Bujairami",
    "inspiration": "Rasasi - Hawas ICE",
    "status": "In stock",
    "emojis": "❄🧊🌬",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bujairami%20ICE",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "The Aftermath",
    "house": "Bujairami",
    "inspiration": "Original Creation",
    "status": "In stock",
    "emojis": "🔥🌫🪵",
    "p3": "$5",
    "p5": "$7",
    "p10": "$11",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Bujairami/The-Aftermath-89278.html",
    "category": "Smoky Woods",
    "occasion": "Daily / Versatile",
    "notes": "smoky woods, amber, warm spice"
  },
  {
    "name": "Star",
    "house": "Bujairami",
    "inspiration": "Versace - Eros Najim",
    "status": "In stock",
    "emojis": "🍬🌙🪵",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bujairami%20Star",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Ozonic",
    "house": "Bujairami",
    "inspiration": "Wavechild - Room 1015",
    "status": "In stock",
    "emojis": "🍊🥥🌅",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Bujairami/Ozonic-123802.html",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Casanova",
    "house": "Bujairami",
    "inspiration": "Xerjoff - XJ 1861 Naxos",
    "status": "In stock",
    "emojis": "🚬🍯🎩",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bujairami%20Casanova",
    "category": "Honey Tobacco",
    "occasion": "Date / Autumn",
    "notes": "honey, citrus, tobacco, vanilla"
  },
  {
    "name": "The Most Wanted Intense",
    "house": "Designer",
    "inspiration": "Azzaro - The Most Wanted Intense",
    "status": "In stock",
    "emojis": "🧨🌶🍮",
    "p3": "$9",
    "p5": "$15",
    "p10": "$30",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Azzaro/The-Most-Wanted-Intense-90953.html",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Nuit d'Issey EDT",
    "house": "Designer",
    "inspiration": "Issey Miyake - Nuit d'Issey",
    "status": "In stock",
    "emojis": "🌒🔥🖤",
    "p3": "$4",
    "p5": "$7",
    "p10": "$10",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Issey-Miyake/Nuit-d-Issey-25514.html",
    "imageUrl": "https://fimgs.net/mdimg/perfume/375x500.25514.jpg",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Fusion d'Issey Extrême",
    "house": "Designer",
    "inspiration": "Issey Miyake - Fusion d'Issey Extrême",
    "status": "In stock",
    "emojis": "🌋🌴🌿",
    "p3": "$7",
    "p5": "$11",
    "p10": "$18",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Issey-Miyake/Fusion-d-Issey-Extreme-67524.html",
    "imageUrl": "https://fimgs.net/mdimg/perfume/375x500.67524.jpg",
    "category": "Tropical Woody",
    "occasion": "Daily / Versatile",
    "notes": "mint, coconut, mineral notes, sandalwood"
  },
  {
    "name": "L'Eau d'Issey Intense",
    "house": "Designer",
    "inspiration": "Issey Miyake - L'Eau d'Issey Pour Homme Intense",
    "status": "In stock",
    "emojis": "🍊🕯🌲",
    "p3": "$6",
    "p5": "$10",
    "p10": "$17",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Issey-Miyake/L-Eau-d-Issey-Pour-Homme-Intense-1998.html",
    "imageUrl": "https://fimgs.net/mdimg/perfume/375x500.1998.jpg",
    "category": "Citrus Incense",
    "occasion": "Daily / Summer",
    "notes": "yuzu, spice, incense, amber, papyrus"
  },
  {
    "name": "Boss Bottled EDT",
    "house": "Designer",
    "inspiration": "Hugo Boss - Boss Bottled",
    "status": "In stock",
    "emojis": "🍏🌿✨",
    "p3": "$4",
    "p5": "$7",
    "p10": "$10",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Hugo-Boss/Boss-Bottled-383.html",
    "imageUrl": "https://fimgs.net/mdimg/perfume/375x500.383.jpg",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Boss Bottled Absolu Parfum",
    "house": "Designer",
    "inspiration": "Hugo Boss - Boss Bottled Absolu Intense",
    "status": "In stock",
    "emojis": "🌶🔥🍂",
    "p3": "$10",
    "p5": "$17",
    "p10": "$30",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Hugo-Boss/Bottled-Absolu-96246.html",
    "imageUrl": "https://fimgs.net/mdimg/perfume/375x500.96246.jpg",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Boss Bottled Parfum",
    "house": "Designer",
    "inspiration": "Hugo Boss - Boss Bottled Parfum",
    "status": "In stock",
    "emojis": "🍎🌳🧴",
    "p3": "$8",
    "p5": "$13",
    "p10": "$20",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Hugo-Boss/Boss-Bottled-Parfum-75183.html",
    "imageUrl": "https://fimgs.net/mdimg/perfume/375x500.75183.jpg",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Acqua di Giò Eau de Parfum",
    "house": "Designer",
    "inspiration": "Armani - Acqua di Giò Eau de Parfum",
    "status": "In stock",
    "emojis": "🌊🍋🪵",
    "p3": "$8",
    "p5": "$13",
    "p10": "$22",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Giorgio-Armani/Acqua-di-Gio-Eau-de-Parfum-71606.html",
    "imageUrl": "https://fimgs.net/mdimg/perfume/375x500.71606.jpg",
    "category": "Aquatic",
    "occasion": "Daily / Summer",
    "notes": "marine notes, citrus, woods"
  },
  {
    "name": "Cedrat Boise",
    "house": "Designer",
    "inspiration": "Mancera - Cedrat Boise",
    "status": "In stock",
    "emojis": "🍋🖤🪵",
    "p3": "$7",
    "p5": "$11",
    "p10": "$15",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Mancera/Cedrat-Boise-15211.html",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Grand Soir",
    "house": "Designer",
    "inspiration": "MFK - Grand Soir",
    "status": "In stock",
    "emojis": "🌌🔥🍯",
    "p3": "$18",
    "p5": "$40",
    "p10": "$65",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Grand-Soir-40816.html",
    "category": "Amber",
    "occasion": "Date / Autumn",
    "notes": "amber, vanilla, benzoin"
  },
  {
    "name": "1 Million - Royal",
    "house": "Designer",
    "inspiration": "Paco Rabanne - 1M Royal",
    "status": "In stock",
    "emojis": "🏰🌿🌌",
    "p3": "$8",
    "p5": "$18",
    "p10": "$30",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Rabanne/1-Million-Royal-79159.html",
    "category": "Sweet / Aromatic",
    "occasion": "Date / Autumn",
    "notes": "lavender, woods, sweetness"
  },
  {
    "name": "Polo 67 EDP",
    "house": "Designer",
    "inspiration": "Ralph Lauren - Polo 67",
    "status": "In stock",
    "emojis": "🍍🌿🪵",
    "p3": "$6",
    "p5": "$14",
    "p10": "$20",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Ralph-Lauren/Polo-67-Eau-de-Parfum-108720.html",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Spicebomb Metallic Musk",
    "house": "Designer",
    "inspiration": "Viktor&Rolf - SpiceBomb Metallic Musk",
    "status": "In stock",
    "emojis": "🧊🧥💿",
    "p3": "$8",
    "p5": "$13",
    "p10": "$22",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Viktor-Rolf/Spicebomb-Metallic-Musk-104937.html",
    "imageUrl": "https://fimgs.net/mdimg/perfume/375x500.104937.jpg",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Spicebomb Infrared EDP",
    "house": "Designer",
    "inspiration": "Viktor&Rolf - SpiceBomb Infrared",
    "status": "In stock",
    "emojis": "🌶🔥🍬",
    "p3": "$8",
    "p5": "$13",
    "p10": "$22",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Viktor-Rolf/Spicebomb-Infrared-Eau-de-Parfum-81409.html",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Born in Roma Coral Fantasy EDT",
    "house": "Designer",
    "inspiration": "Valentino - Born in Roma Coral Fantasy",
    "status": "In stock",
    "emojis": "🍎🌿🎩",
    "p3": "$8",
    "p5": "$17",
    "p10": "$30",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Valentino/Valentino-Uomo-Born-In-Roma-Coral-Fantasy-71761.html",
    "category": "Fruity Sweet",
    "occasion": "Date / Autumn",
    "notes": "apple, woods, amber sweetness"
  },
  {
    "name": "XJ 1861 Naxos",
    "house": "Designer",
    "inspiration": "Xerjoff - Naxos",
    "status": "In stock",
    "emojis": "🍯🍊🍂",
    "p3": "$14",
    "p5": "$27",
    "p10": "$50",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Xerjoff/XJ-1861-Naxos-30529.html",
    "imageUrl": "https://fimgs.net/mdimg/perfume/375x500.30529.jpg",
    "category": "Honey Tobacco",
    "occasion": "Date / Autumn",
    "notes": "honey, citrus, tobacco, vanilla"
  },
  {
    "name": "Royal Taboo Extrait",
    "house": "French Avenue",
    "inspiration": "Creed - Centaurus",
    "status": "In stock",
    "emojis": "👑🕰🌿",
    "p3": "$4",
    "p5": "$7",
    "p10": "$10",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Aromatix-X-French-Avenue/Royal-Taboo-99330.html",
    "category": "Spicy Amber",
    "occasion": "Date / Autumn",
    "notes": "spice, tobacco nuance, woods"
  },
  {
    "name": "Teas Me Extrait",
    "house": "French Avenue",
    "inspiration": "Nishane - Wulóng Chá",
    "status": "In stock",
    "emojis": "🍋🍵✨",
    "p3": "$4",
    "p5": "$7",
    "p10": "$10",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Aromatix-X-French-Avenue/Teas-Me-117532.html",
    "imageUrl": "https://fimgs.net/mdimg/perfume/375x500.117532.jpg",
    "category": "Tea Fresh",
    "occasion": "Daily / Summer",
    "notes": "citrus, tea, clean musk"
  },
  {
    "name": "Lumière Garçon",
    "house": "French Avenue",
    "inspiration": "D&G - The One Luminous Night",
    "status": "In stock",
    "emojis": "🌙🌴🧂",
    "p3": "$4",
    "p5": "$6",
    "p10": "$11",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/French-Avenue/Lumiere-Garcon-94712.html",
    "category": "Fragrance",
    "occasion": "Date / Autumn",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Obsidian",
    "house": "French Avenue",
    "inspiration": "By Kilian - Angels Share on the Rocks",
    "status": "In stock",
    "emojis": "🧊🍊🥃",
    "p3": "$6",
    "p5": "$9",
    "p10": "$14",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/French-Avenue/Obsidian-120872.html",
    "category": "Boozy Sweet",
    "occasion": "Date / Autumn",
    "notes": "cognac, spice, oak, vanilla warmth"
  },
  {
    "name": "Moonstone Bleu",
    "house": "French Avenue",
    "inspiration": "Penhaligons - Sartorial",
    "status": "In stock",
    "emojis": "💎🌊🧼",
    "p3": "$4",
    "p5": "$8",
    "p10": "$10",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/French-Avenue/Moonstone-Bleu-100011.html",
    "category": "Clean / Aromatic",
    "occasion": "Daily / Versatile",
    "notes": "metallic fresh, lavender, woods"
  },
  {
    "name": "Mexican Tobacco Extrait",
    "house": "Ibraheem AlQurashi",
    "inspiration": "Jeroboam - Gozo",
    "status": "In stock",
    "emojis": "🍫🌹🔥",
    "p3": "$10",
    "p5": "N/A",
    "p10": "N/A",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Ibraheem-AlQurashi/Mexican-Tobacco-100563.html",
    "category": "Tobacco",
    "occasion": "Date / Autumn",
    "notes": "tobacco, warmth, spice"
  },
  {
    "name": "Jamaican Tobacco Extrait",
    "house": "Ibraheem AlQurashi",
    "inspiration": "Ex Nihilo - Brompton Immortals Extrait",
    "status": "In stock",
    "emojis": "🌿🪵🌫",
    "p3": "$10",
    "p5": "N/A",
    "p10": "N/A",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Ibraheem-AlQurashi/Jamaican-Tobacco-100564.html",
    "category": "Tobacco",
    "occasion": "Date / Autumn",
    "notes": "tobacco, warmth, spice"
  },
  {
    "name": "Cuban Tobacco Extrait",
    "house": "Ibraheem AlQurashi",
    "inspiration": "Le Labo - Tabac 28",
    "status": "In stock",
    "emojis": "🍯🍫🥃",
    "p3": "$10",
    "p5": "N/A",
    "p10": "N/A",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Ibraheem%20AlQurashi%20Cuban%20Tobacco%20Extrait",
    "category": "Tobacco",
    "occasion": "Date / Autumn",
    "notes": "tobacco, warmth, spice"
  },
  {
    "name": "Greek Tobacco Extrait",
    "house": "Ibraheem AlQurashi",
    "inspiration": "Ex Nihilo - Fleur Narcotique",
    "status": "In stock",
    "emojis": "🌸🍑🌹",
    "p3": "$8",
    "p5": "$13",
    "p10": "$22",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Ibraheem-AlQurashi/Greek-Tobacco-100553.html",
    "category": "Tobacco",
    "occasion": "Date / Autumn",
    "notes": "tobacco, warmth, spice"
  },
  {
    "name": "Spanish Tobacco Extrait",
    "house": "Ibraheem AlQurashi",
    "inspiration": "Orto Parisi - Megamare",
    "status": "In stock",
    "emojis": "🌊🪵🫧",
    "p3": "$10",
    "p5": "N/A",
    "p10": "N/A",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Ibraheem-AlQurashi/Spanish-Tobacco-100551.html",
    "category": "Tobacco",
    "occasion": "Date / Autumn",
    "notes": "tobacco, warmth, spice"
  },
  {
    "name": "French Tobacco Extrait",
    "house": "Ibraheem AlQurashi",
    "inspiration": "Louis Vuitton - Imagination",
    "status": "In stock",
    "emojis": "🍊🍃🧼",
    "p3": "$10",
    "p5": "N/A",
    "p10": "N/A",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Ibraheem-AlQurashi/French-Tobacco-100552.html",
    "category": "Tobacco",
    "occasion": "Date / Autumn",
    "notes": "tobacco, warmth, spice"
  },
  {
    "name": "Brazillian Tobacco Extrait",
    "house": "Ibraheem AlQurashi",
    "inspiration": "Parfums de Marly - Haltane",
    "status": "In stock",
    "emojis": "🌶🍒🧥",
    "p3": "$10",
    "p5": "N/A",
    "p10": "N/A",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Ibraheem-AlQurashi/Brazilian-Tobacco-100562.html",
    "category": "Tobacco",
    "occasion": "Date / Autumn",
    "notes": "tobacco, warmth, spice"
  },
  {
    "name": "Tonka Powder",
    "house": "Jalu",
    "inspiration": "Hybrid - A Tonka/V Powder",
    "status": "In stock",
    "emojis": "🧁✨🕯",
    "p3": "$6",
    "p5": "$11",
    "p10": "$15",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Jalu%20Tonka%20Powder",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Triumvrate",
    "house": "Jalu",
    "inspiration": "Hybrid - MYSLF/Y + Bubblegum",
    "status": "In stock",
    "emojis": "🍬🌿🍋",
    "p3": "$6",
    "p5": "$11",
    "p10": "$15",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Jalu%20Triumvrate",
    "category": "Fresh Sweet",
    "occasion": "Daily / Summer",
    "notes": "fresh citrus, florals, bubblegum sweetness"
  },
  {
    "name": "Purple Haze",
    "house": "Jalu",
    "inspiration": "Hybrid - Erba Pura/Rouge Trafalgar",
    "status": "In stock",
    "emojis": "🍊🌸🌿",
    "p3": "$6",
    "p5": "$11",
    "p10": "$15",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Jalu%20Purple%20Haze",
    "category": "Fruity Sweet",
    "occasion": "Date / Autumn",
    "notes": "citrus, fruit, musk, amber"
  },
  {
    "name": "Jaguar",
    "house": "Jalu",
    "inspiration": "Hybrid - L'Immensite/Tygar",
    "status": "In stock",
    "emojis": "🫚🐅🍊",
    "p3": "$6",
    "p5": "$11",
    "p10": "$15",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Jalu%20Jaguar",
    "category": "Ginger Citrus",
    "occasion": "Daily / Summer",
    "notes": "ginger, grapefruit, amber woods"
  },
  {
    "name": "Nirvana",
    "house": "Jalu",
    "inspiration": "Roja - Elysium Pour Homme Parfum",
    "status": "In stock",
    "emojis": "🍋🌿✨",
    "p3": "$6",
    "p5": "$11",
    "p10": "$15",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Jalu%20Nirvana",
    "category": "Iris / Leather",
    "occasion": "Date / Autumn",
    "notes": "iris, amber, woods, leather nuance"
  },
  {
    "name": "SANAYA",
    "house": "Junaid",
    "inspiration": "LV - Imagination",
    "status": "In stock",
    "emojis": "🫧🧊🌿",
    "p3": "$6",
    "p5": "$11",
    "p10": "$18",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Junaid%20SANAYA",
    "category": "Citrus Tea",
    "occasion": "Daily / Summer",
    "notes": "citrus, ginger, tea, clean amber"
  },
  {
    "name": "Emeer",
    "house": "Lattafa",
    "inspiration": "Clive Christian - Town & Country",
    "status": "In stock",
    "emojis": "🍋🌿🪵",
    "p3": "$4",
    "p5": "$6",
    "p10": "$9",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Lattafa%20Emeer",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Masa",
    "house": "Lattafa",
    "inspiration": "Marc-Antoine Barrois - Ganymede",
    "status": "In stock",
    "emojis": "🪨✨🍊",
    "p3": "$6",
    "p5": "$10",
    "p10": "$15",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Masa-92484.html",
    "imageUrl": "https://fimgs.net/mdimg/perfume/375x500.92484.jpg",
    "category": "Mineral Woods",
    "occasion": "Daily / Versatile",
    "notes": "mineral citrus, suede-like woods"
  },
  {
    "name": "Musamam Black Intense",
    "house": "Lattafa",
    "inspiration": "Unique",
    "status": "In stock",
    "emojis": "🖤🌲🍫",
    "p3": "$8",
    "p5": "$14",
    "p10": "$23",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Lattafa%20Musamam%20Black%20Intense",
    "category": "Woody Sweet",
    "occasion": "Date / Autumn",
    "notes": "woody spice, tonka, maple sweetness"
  },
  {
    "name": "Opulent Dubai",
    "house": "Lattafa",
    "inspiration": "SHL - God of Fire",
    "status": "In stock",
    "emojis": "🌴🥭✨",
    "p3": "$5",
    "p5": "$8",
    "p10": "$14",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Opulent-Dubai-105609.html",
    "imageUrl": "https://fimgs.net/mdimg/perfume/375x500.105609.jpg",
    "category": "Tropical Fruity",
    "occasion": "Daily / Versatile",
    "notes": "mango, citrus, ginger, amber woods"
  },
  {
    "name": "Atlas",
    "house": "Lattafa",
    "inspiration": "Orto Parisi - Megamare",
    "status": "In stock",
    "emojis": "🌊⚪🫧",
    "p3": "$7",
    "p5": "$11",
    "p10": "$14",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Lattafa%20Atlas",
    "category": "Marine / Powerful",
    "occasion": "Daily / Summer",
    "notes": "marine, salty woods, musky amber"
  },
  {
    "name": "Jasoor",
    "house": "Lattafa",
    "inspiration": "Valentino - Born in Roma Coral Fantasy",
    "status": "In stock",
    "emojis": "🍎🍂🪵",
    "p3": "$6",
    "p5": "$8",
    "p10": "$11",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Lattafa%20Jasoor",
    "category": "Fruity Sweet",
    "occasion": "Date / Autumn",
    "notes": "apple, woods, amber sweetness"
  },
  {
    "name": "Vintage Radio",
    "house": "Lattafa",
    "inspiration": "Initio Parfums Prives - Paragon",
    "status": "In stock",
    "emojis": "📻🍇🌲",
    "p3": "$6",
    "p5": "$8",
    "p10": "$12",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Lattafa%20Vintage%20Radio",
    "category": "Fruity Woody",
    "occasion": "Daily / Versatile",
    "notes": "plum, sage, palo santo, woods"
  },
  {
    "name": "Art of Nature II",
    "house": "Lattafa",
    "inspiration": "Parfums de Marly - Althaïr",
    "status": "In stock",
    "emojis": "🍊🍦🎩",
    "p3": "$4",
    "p5": "$6",
    "p10": "$9",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Art-Of-Nature-II-98242.html",
    "category": "Vanilla / Sweet",
    "occasion": "Date / Autumn",
    "notes": "vanilla, citrus, amber woods"
  },
  {
    "name": "Teriaq Intense",
    "house": "Lattafa",
    "inspiration": "Unique",
    "status": "In stock",
    "emojis": "🥃🕯🌌",
    "p3": "$6",
    "p5": "$11",
    "p10": "$15",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Lattafa%20Teriaq%20Intense",
    "category": "Amber / Night",
    "occasion": "Date / Autumn",
    "notes": "boozy amber, spice, dark warmth"
  },
  {
    "name": "Ana Abiyedh - Rouge (W)",
    "house": "Lattafa",
    "inspiration": "MFK - Baccarat Rouge 540",
    "status": "In stock",
    "emojis": "🍐🍬✨",
    "p3": "$5",
    "p5": "$7",
    "p10": "$12",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Ana-Abiyedh-Rouge-63062.html",
    "imageUrl": "https://fimgs.net/mdimg/perfume/375x500.63062.jpg",
    "category": "Sweet Amber",
    "occasion": "Date / Autumn",
    "notes": "airy amber, sweet musk"
  },
  {
    "name": "Luxe Street",
    "house": "Maison Alhambra",
    "inspiration": "Bond No.9 - Lafayette St.",
    "status": "In stock",
    "emojis": "🪻🍎🗽",
    "p3": "$5",
    "p5": "$7",
    "p10": "$12",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Maison%20Alhambra%20Luxe%20Street",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Luxe Chic (W)",
    "house": "Maison Alhambra",
    "inspiration": "Bond No.9 - Nolita",
    "status": "In stock",
    "emojis": "🌸💄🍓",
    "p3": "$5",
    "p5": "$7",
    "p10": "$12",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Maison%20Alhambra%20Luxe%20Chic%20%28W%29",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Winsome",
    "house": "Maison Alhambra",
    "inspiration": "Yves Saint Laurent - Tuxedo",
    "status": "In stock",
    "emojis": "🖤🧥🥂",
    "p3": "$6",
    "p5": "$8",
    "p10": "$11",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Maison%20Alhambra%20Winsome",
    "category": "Amber / Dressy",
    "occasion": "Date / Autumn",
    "notes": "patchouli, amber, rose, vanilla"
  },
  {
    "name": "Legacy",
    "house": "Maison Asrar",
    "inspiration": "Ex Nihilo - Blue Talisman",
    "status": "In stock",
    "emojis": "🍐✨🌿",
    "p3": "$6",
    "p5": "$9",
    "p10": "$14",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Maison%20Asrar%20Legacy",
    "category": "Fruity Fresh",
    "occasion": "Daily / Summer",
    "notes": "pear, ginger, orange blossom, musk"
  },
  {
    "name": "Rifaqaat",
    "house": "Paris Corner",
    "inspiration": "Yves Saint Laurent - Babycat",
    "status": "In stock",
    "emojis": "🐆🍦🔥",
    "p3": "$5",
    "p5": "$7",
    "p10": "$12",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Paris%20Corner%20Rifaqaat",
    "category": "Vanilla Amber",
    "occasion": "Date / Autumn",
    "notes": "vanilla, resin, suede-like warmth"
  },
  {
    "name": "Tiger [Cal Cologne]",
    "house": "Rayhaan",
    "inspiration": "Penhaligon's - Halfeti",
    "status": "In stock",
    "emojis": "🐅🌶🌹",
    "p3": "$6",
    "p5": "$10",
    "p10": "$15",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Rayhaan%20Tiger",
    "category": "Spicy Rose",
    "occasion": "Daily / Versatile",
    "notes": "rose, spice, woods, amber"
  },
  {
    "name": "Seasons Drift",
    "house": "Riffs",
    "inspiration": "Chanel - Bleu de Chanel L’Exclusif",
    "status": "In stock",
    "emojis": "🌊🌲🖤",
    "p3": "$6",
    "p5": "$10",
    "p10": "$15",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Riffs%20Seasons%20Drift",
    "category": "Blue / Woody",
    "occasion": "Daily / Summer",
    "notes": "citrus, woods, amber, incense"
  },
  {
    "name": "Cardamom and Apple",
    "house": "Swiss Arabian",
    "inspiration": "Armani - Code Profumo",
    "status": "In stock",
    "emojis": "🍏🌿✨",
    "p3": "$6",
    "p5": "$11",
    "p10": "$18",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Swiss%20Arabian%20Cardamom%20and%20Apple",
    "category": "Aquatic Incense",
    "occasion": "Daily / Summer",
    "notes": "marine notes, incense, woods"
  },
  {
    "name": "Incense 01 Extrait",
    "house": "Swiss Arabian",
    "inspiration": "Original Creation",
    "status": "In stock",
    "emojis": "🕯🌰💨",
    "p3": "$10",
    "p5": "$20",
    "p10": "$30",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Swiss-Arabian/Incense-01-102415.html",
    "imageUrl": "https://fimgs.net/mdimg/perfume/375x500.102415.jpg",
    "category": "Incense Gourmand",
    "occasion": "Date / Autumn",
    "notes": "incense, nutty sweetness, woods"
  }
];

const packs = [
  {
    "name": "Night Out Pack",
    "emojis": "🌙🔥🥃",
    "price": "3 x 3mL — $15",
    "items": [
      "9PM - Night Out Extrait",
      "Spicebomb Infrared EDP",
      "Booz Extreme"
    ],
    "desc": "Sweet, loud and built for dates, drinks and going out."
  },
  {
    "name": "Clean Luxury Pack",
    "emojis": "🤍🍋✨",
    "price": "3 x 3mL — $18",
    "items": [
      "SANAYA",
      "Nirvana",
      "Iris Infinite Extrait"
    ],
    "desc": "Fresh, clean and expensive-smelling."
  },
  {
    "name": "Tropical Pack",
    "emojis": "🥭🍍🍋",
    "price": "3 x 3mL — $15",
    "items": [
      "Opulent Dubai",
      "Supremacy Collectors Ed.",
      "SANAYA"
    ],
    "desc": "Bright fruity warm-weather scents."
  },
  {
    "name": "Arabian Power Pack",
    "emojis": "🐎🖤🔥",
    "price": "3 x 3mL — $20",
    "items": [
      "Wild Colt",
      "Musamam Black Intense",
      "Ignite Oud Extrait"
    ],
    "desc": "Strong Middle Eastern-style performers."
  },
  {
    "name": "Office Boss Pack",
    "emojis": "💼🌲🧼",
    "price": "3 x 3mL — $18",
    "items": [
      "Seasons Drift",
      "Boss Bottled Parfum",
      "Masa"
    ],
    "desc": "Polished daily scents for work, meetings and smart casual wear."
  },
  {
    "name": "Sweet Starter Pack",
    "emojis": "🍬✨🥃",
    "price": "3 x 3mL — $15",
    "items": [
      "Ana Abiyedh - Rouge (W)",
      "Booz",
      "Art of Nature II"
    ],
    "desc": "Sweet, easy and compliment-focused."
  }
];
