// DeadEnd Scents catalogue data. Update this file when your fragrance list changes.
window.siteConfig = {
  "facebookMessengerUrl": "https://m.me/nickstreet09/",
  "whatsAppUrl": "https://wa.me/61434432948?text=Hi%20DeadEnd%20Scents%2C%20I%27d%20like%20to%20order%20some%20samples.",
  "instagramUrl": "https://instagram.com/deadendscents",
  "businessName": "DeadEnd Scents"
};

const fragrances = [
  {
    "name": "Supremacy Collectors Ed.",
    "house": "Afnan",
    "inspiration": "Creed - Absolu Aventus",
    "status": "In stock",
    "emojis": "🍍🪵🌫",
    "p3": "$6",
    "p5": "$11",
    "p10": "$14",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Afnan/Supremacy-Collector-s-Edition-Pour-Homme-98689.html",
    "category": "Fruity Woods",
    "occasion": "Daily / Versatile",
    "notes": "pineapple, citrus, smoky woods"
  },
  {
    "name": "Supremacy in Heaven",
    "house": "Afnan",
    "inspiration": "Creed - Silver Mountain Water",
    "status": "In stock",
    "emojis": "🍊🌿🪵",
    "p3": "$5",
    "p5": "$9",
    "p10": "$13",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Afnan/Supremacy-In-Heaven-70703.html",
    "category": "Fresh / Clean",
    "occasion": "Daily / Summer",
    "notes": "citrus, green tea, clean musk"
  },
  {
    "name": "9PM - Night Out Extrait",
    "house": "Afnan",
    "inspiration": "Original Creation",
    "status": "In stock",
    "emojis": "🍏🥃🧥",
    "p3": "$6",
    "p5": "$9",
    "p10": "$13",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Afnan%209PM%20-%20Night%20Out%20Extrait",
    "category": "Fruity / Night Out",
    "occasion": "Date / Autumn",
    "notes": "dragon fruit, apple, cognac, toffee, suede, tonka"
  },
  {
    "name": "Kaaf Extrait",
    "house": "Ahmed Al Maghrabi",
    "inspiration": "Parfums de Marly - Percival",
    "status": "In stock",
    "emojis": "🍋🧼🌿",
    "p3": "$4",
    "p5": "$7",
    "p10": "$12",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Ahmed-Al-Maghribi/Kaaf-102460.html",
    "category": "Fresh / Clean",
    "occasion": "Daily / Summer",
    "notes": "citrus, lavender, clean musk"
  },
  {
    "name": "Aqua Oud",
    "house": "Ahmed Al Maghrabi",
    "inspiration": "Armani - Acqua di Giò Profumo",
    "status": "In stock",
    "emojis": "🌊🪵🕌",
    "p3": "$5",
    "p5": "$8",
    "p10": "$12",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Ahmed-Al-Maghribi/Aqua-Oud-111001.html",
    "category": "Aquatic",
    "occasion": "Daily / Summer",
    "notes": "marine notes, citrus, woods"
  },
  {
    "name": "Ignite Oud Extrait",
    "house": "Ahmed Al Maghrabi",
    "inspiration": "Original Creation",
    "status": "In stock",
    "emojis": "🔥🧥🌲",
    "p3": "$9",
    "p5": "$15",
    "p10": "$28",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Ahmed%20Al%20Maghrabi%20Ignite%20Oud%20Extrait",
    "category": "Woody Leather",
    "occasion": "Date / Autumn",
    "notes": "leather, patchouli, cedar, amber"
  },
  {
    "name": "Club de Nuit Precieux I",
    "house": "ARMAF",
    "inspiration": "Creed - Absolu Aventus",
    "status": "In stock",
    "emojis": "🪵🍍🌫",
    "p3": "$6",
    "p5": "$11",
    "p10": "$14",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Armaf/Club-de-Nuit-Precieux-I-93272.html",
    "category": "Fruity Woods",
    "occasion": "Daily / Versatile",
    "notes": "pineapple, citrus, smoky woods"
  },
  {
    "name": "Club de Nuit Intense Man EDT",
    "house": "ARMAF",
    "inspiration": "Creed - Aventus",
    "status": "In stock",
    "emojis": "🍍🌲🔥",
    "p3": "$5",
    "p5": "$8",
    "p10": "$13",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Armaf/Club-de-Nuit-Intense-Man-34696.html",
    "category": "Fruity Woods",
    "occasion": "Daily / Versatile",
    "notes": "pineapple, citrus, smoky woods"
  },
  {
    "name": "Wild Colt",
    "house": "Assaf",
    "inspiration": "Gissah - Imperial Valley",
    "status": "In stock",
    "emojis": "🐎🧥🍋",
    "p3": "$6",
    "p5": "$11",
    "p10": "$18",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Assaf/Wild-Colt-Elixir-75834.html",
    "category": "Leather / Woody",
    "occasion": "Date / Autumn",
    "notes": "saffron, grapefruit, leather, patchouli, ambergris"
  },
  {
    "name": "Boss Life Extrait",
    "house": "Bujairami",
    "inspiration": "Amouage - Outlands",
    "status": "In stock",
    "emojis": "🌙🔥🌿",
    "p3": "$5",
    "p5": "$8",
    "p10": "$12",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Amouage%20-%20Outlands",
    "category": "Amber / Aromatic",
    "occasion": "Date / Autumn",
    "notes": "warm spice, amber, aromatic woods"
  },
  {
    "name": "Kingsman Extrait",
    "house": "Bujairami",
    "inspiration": "Creed - Aventus",
    "status": "In stock",
    "emojis": "🍍🪵👑",
    "p3": "$5",
    "p5": "$8",
    "p10": "$12",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Creed%20-%20Aventus",
    "category": "Fruity Woods",
    "occasion": "Daily / Versatile",
    "notes": "pineapple, citrus, smoky woods"
  },
  {
    "name": "Gladiator",
    "house": "Bujairami",
    "inspiration": "Argos - Triumph of Bacchus",
    "status": "In stock",
    "emojis": "🍎🥃🏛",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Argos%20-%20Triumph%20of%20Bacchus",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Emperor",
    "house": "Bujairami",
    "inspiration": "Creed - Absolu Aventus",
    "status": "In stock",
    "emojis": "🍍🪵🔥",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Creed%20-%20Absolu%20Aventus",
    "category": "Fruity Woods",
    "occasion": "Daily / Versatile",
    "notes": "pineapple, citrus, smoky woods"
  },
  {
    "name": "Aqua Pure",
    "house": "Bujairami",
    "inspiration": "Armani - Acqua di Giò Absolu",
    "status": "In stock",
    "emojis": "🌊🍊🪵",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Armani%20-%20Acqua%20di%20Gi%C3%B2%20Absolu",
    "category": "Aquatic",
    "occasion": "Daily / Summer",
    "notes": "marine notes, citrus, woods"
  },
  {
    "name": "The Rock Intensely",
    "house": "Bujairami",
    "inspiration": "Armani - SWY Intensely",
    "status": "In stock",
    "emojis": "🔥🍦🌰",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Armani%20-%20SWY%20Intensely",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Gotham",
    "house": "Bujairami",
    "inspiration": "Bond No.9 - Bleecker St.",
    "status": "In stock",
    "emojis": "🦇🌃🔥",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bond%20No.9%20-%20Bleecker%20St.",
    "category": "Green Fruity",
    "occasion": "Daily / Summer",
    "notes": "blueberry, violet leaf, woods"
  },
  {
    "name": "Ocean Drip",
    "house": "Bujairami",
    "inspiration": "Bvlgari - Aqva Pour Homme Atlantiqve",
    "status": "In stock",
    "emojis": "🌊🌀❄",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bvlgari%20-%20Aqva%20Pour%20Homme%20Atlantiqve",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Mafia Boss Extrait",
    "house": "Bujairami",
    "inspiration": "Clive Christian - Blonde Amber",
    "status": "In stock",
    "emojis": "🍦🥃🕴",
    "p3": "$5",
    "p5": "$8",
    "p10": "$12",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Clive%20Christian%20-%20Blonde%20Amber",
    "category": "Amber / Boozy",
    "occasion": "Date / Autumn",
    "notes": "amber, vanilla, booze, woods"
  },
  {
    "name": "High Tide Mojito",
    "house": "Bujairami",
    "inspiration": "Clive Christian - Crab Apple Blossom",
    "status": "In stock",
    "emojis": "🌊🍃🍏",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Clive%20Christian%20-%20Crab%20Apple%20Blossom",
    "category": "Fresh Fruity",
    "occasion": "Daily / Summer",
    "notes": "apple, marine notes, mint"
  },
  {
    "name": "Bossman Extrait",
    "house": "Bujairami",
    "inspiration": "Creed - Absolu Aventus (2025)",
    "status": "In stock",
    "emojis": "💼🍍🔥",
    "p3": "$5",
    "p5": "$8",
    "p10": "$12",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Creed%20-%20Absolu%20Aventus%20%282025%29",
    "category": "Fruity Woods",
    "occasion": "Daily / Versatile",
    "notes": "pineapple, citrus, smoky woods"
  },
  {
    "name": "Finesse (W)",
    "house": "Bujairami",
    "inspiration": "Dior - Blooming Bouquet",
    "status": "In stock",
    "emojis": "🌸🍑🎀",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Dior%20-%20Blooming%20Bouquet",
    "category": "Floral",
    "occasion": "Daily / Feminine",
    "notes": "peony, rose, peach"
  },
  {
    "name": "Romantic Rose (W)",
    "house": "Bujairami",
    "inspiration": "Initio Parfums Prives - Atomic Rose",
    "status": "In stock",
    "emojis": "🌹💥🔥",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Initio%20Parfums%20Prives%20-%20Atomic%20Rose",
    "category": "Rose Amber",
    "occasion": "Date / Autumn",
    "notes": "rose, vanilla, amber"
  },
  {
    "name": "Booz Extreme",
    "house": "Bujairami",
    "inspiration": "By Kilian - Angels Share",
    "status": "In stock",
    "emojis": "🥃🔥🪵",
    "p3": "$5",
    "p5": "$7",
    "p10": "$11",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=By%20Kilian%20-%20Angels%20Share",
    "category": "Boozy Sweet",
    "occasion": "Date / Autumn",
    "notes": "cognac, spice, oak, vanilla warmth"
  },
  {
    "name": "Shu Helou",
    "house": "Bujairami",
    "inspiration": "Chanel - Bleu de Chanel EDP",
    "status": "In stock",
    "emojis": "🍋🌿🪵",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Chanel%20-%20Bleu%20de%20Chanel%20EDP",
    "category": "Blue / Woody",
    "occasion": "Daily / Summer",
    "notes": "citrus, woods, amber, incense"
  },
  {
    "name": "Iris Infinite Extrait",
    "house": "Bujairami",
    "inspiration": "Dior - Homme Parfum 2025",
    "status": "In stock",
    "emojis": "🪻🪾🧥",
    "p3": "$5",
    "p5": "$8",
    "p10": "$12",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Dior%20-%20Homme%20Parfum%202025",
    "category": "Iris / Leather",
    "occasion": "Date / Autumn",
    "notes": "iris, amber, woods, leather nuance"
  },
  {
    "name": "Midnight Booz",
    "house": "Bujairami",
    "inspiration": "By Kilian - Angels Share Paradis",
    "status": "In stock",
    "emojis": "🍇🛋🥃",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=By%20Kilian%20-%20Angels%20Share%20Paradis",
    "category": "Boozy Sweet",
    "occasion": "Date / Autumn",
    "notes": "cognac, spice, oak, vanilla warmth"
  },
  {
    "name": "High Roller",
    "house": "Bujairami",
    "inspiration": "Valentino - Born in Roma Extradose",
    "status": "In stock",
    "emojis": "🎲🍦🌿",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Valentino%20-%20Born%20in%20Roma%20Extradose",
    "category": "Fruity Sweet",
    "occasion": "Date / Autumn",
    "notes": "apple, woods, amber sweetness"
  },
  {
    "name": "Booz",
    "house": "Bujairami",
    "inspiration": "By Kilian - Angels Share Twist",
    "status": "In stock",
    "emojis": "🥃🍏🔥",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=By%20Kilian%20-%20Angels%20Share%20Twist",
    "category": "Boozy Sweet",
    "occasion": "Date / Autumn",
    "notes": "cognac, spice, oak, vanilla warmth"
  },
  {
    "name": "Boujee (W)",
    "house": "Bujairami",
    "inspiration": "Louis Vuitton - Attrape-Rêves",
    "status": "In stock",
    "emojis": "🌸🍫✨",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Louis%20Vuitton%20-%20Attrape-R%C3%AAves",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Riverina Extrait",
    "house": "Bujairami",
    "inspiration": "Original Creation",
    "status": "In stock",
    "emojis": "🌿💧🍊",
    "p3": "$6",
    "p5": "$9",
    "p10": "$15",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bujairami%20Riverina%20Extrait",
    "category": "Fresh / Citrus",
    "occasion": "Daily / Summer",
    "notes": "citrus, green notes, watery freshness"
  },
  {
    "name": "Lucky",
    "house": "Bujairami",
    "inspiration": "Paco Rabanne - 1M Lucky",
    "status": "In stock",
    "emojis": "🌰🍯💰",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Paco%20Rabanne%20-%201M%20Lucky",
    "category": "Sweet / Nutty",
    "occasion": "Date / Autumn",
    "notes": "hazelnut, honey, plum"
  },
  {
    "name": "Untouchable",
    "house": "Bujairami",
    "inspiration": "Paco Rabanne - Invictus Parfum",
    "status": "In stock",
    "emojis": "🛡🌊🏆",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Paco%20Rabanne%20-%20Invictus%20Parfum",
    "category": "Fresh Amber",
    "occasion": "Daily / Summer",
    "notes": "aquatic freshness, amber woods"
  },
  {
    "name": "Wicked",
    "house": "Bujairami",
    "inspiration": "Parfums de Marly - Greenley",
    "status": "In stock",
    "emojis": "🍏🌿💨",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Parfums%20de%20Marly%20-%20Greenley",
    "category": "Green Fruity",
    "occasion": "Daily / Summer",
    "notes": "green apple, woods, musk"
  },
  {
    "name": "Smoldering Sir",
    "house": "Bujairami",
    "inspiration": "Penhaligons - Blazing Mr. Sam",
    "status": "In stock",
    "emojis": "🥃🧴🛋",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Penhaligons%20-%20Blazing%20Mr.%20Sam",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "ICE",
    "house": "Bujairami",
    "inspiration": "Rasasi - Hawas ICE",
    "status": "In stock",
    "emojis": "❄🧊🌬",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Rasasi%20-%20Hawas%20ICE",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "The Aftermath",
    "house": "Bujairami",
    "inspiration": "Original Creation",
    "status": "In stock",
    "emojis": "🔥🌫🪵",
    "p3": "$5",
    "p5": "$7",
    "p10": "$11",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bujairami%20The%20Aftermath",
    "category": "Smoky Woods",
    "occasion": "Daily / Versatile",
    "notes": "smoky woods, amber, warm spice"
  },
  {
    "name": "Star",
    "house": "Bujairami",
    "inspiration": "Versace - Eros Najim",
    "status": "In stock",
    "emojis": "🍬🌙🪵",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Versace%20-%20Eros%20Najim",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Ozonic",
    "house": "Bujairami",
    "inspiration": "Wavechild - Room 1015",
    "status": "In stock",
    "emojis": "🍊🥥🌅",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Wavechild%20-%20Room%201015",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Casanova",
    "house": "Bujairami",
    "inspiration": "Xerjoff - XJ 1861 Naxos",
    "status": "In stock",
    "emojis": "🚬🍯🎩",
    "p3": "$4",
    "p5": "$6",
    "p10": "$8",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Xerjoff%20-%20XJ%201861%20Naxos",
    "category": "Honey Tobacco",
    "occasion": "Date / Autumn",
    "notes": "honey, citrus, tobacco, vanilla"
  },
  {
    "name": "The Most Wanted Intense",
    "house": "Designer",
    "inspiration": "Azzaro - The Most Wanted Intense",
    "status": "In stock",
    "emojis": "🧨🌶🍮",
    "p3": "$9",
    "p5": "$15",
    "p10": "$30",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Azzaro%20-%20The%20Most%20Wanted%20Intense",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Nuit d'Issey EDT",
    "house": "Designer",
    "inspiration": "Issey Miyake - Nuit d'Issey",
    "status": "In stock",
    "emojis": "🌒🔥🖤",
    "p3": "$4",
    "p5": "$7",
    "p10": "$10",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Issey%20Miyake%20-%20Nuit%20d%27Issey",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Fusion d'Issey Extrême",
    "house": "Designer",
    "inspiration": "Issey Miyake - Fusion d'Issey Extrême",
    "status": "In stock",
    "emojis": "🌋🌴🌿",
    "p3": "$7",
    "p5": "$11",
    "p10": "$18",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Issey%20Miyake%20-%20Fusion%20d%27Issey%20Extr%C3%AAme",
    "category": "Tropical Woody",
    "occasion": "Daily / Versatile",
    "notes": "mint, coconut, mineral notes, sandalwood"
  },
  {
    "name": "L'Eau d'Issey Intense",
    "house": "Designer",
    "inspiration": "Issey Miyake - L'Eau d'Issey Pour Homme Intense",
    "status": "In stock",
    "emojis": "🍊🕯🌲",
    "p3": "$6",
    "p5": "$10",
    "p10": "$17",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Issey%20Miyake%20-%20L%27Eau%20d%27Issey%20Pour%20Homme%20Intense",
    "category": "Citrus Incense",
    "occasion": "Daily / Summer",
    "notes": "yuzu, spice, incense, amber, papyrus"
  },
  {
    "name": "Boss Bottled EDT",
    "house": "Designer",
    "inspiration": "Hugo Boss - Boss Bottled",
    "status": "In stock",
    "emojis": "🍏🌿✨",
    "p3": "$4",
    "p5": "$7",
    "p10": "$10",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Hugo%20Boss%20-%20Boss%20Bottled",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Boss Bottled Absolu Parfum",
    "house": "Designer",
    "inspiration": "Hugo Boss - Boss Bottled Absolu Intense",
    "status": "In stock",
    "emojis": "🌶🔥🍂",
    "p3": "$10",
    "p5": "$17",
    "p10": "$30",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Hugo%20Boss%20-%20Boss%20Bottled%20Absolu%20Intense",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Boss Bottled Parfum",
    "house": "Designer",
    "inspiration": "Hugo Boss - Boss Bottled Parfum",
    "status": "In stock",
    "emojis": "🍎🌳🧴",
    "p3": "$8",
    "p5": "$13",
    "p10": "$20",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Hugo%20Boss%20-%20Boss%20Bottled%20Parfum",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Acqua di Giò Eau de Parfum",
    "house": "Designer",
    "inspiration": "Armani - Acqua di Giò Eau de Parfum",
    "status": "In stock",
    "emojis": "🌊🍋🪵",
    "p3": "$8",
    "p5": "$13",
    "p10": "$22",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Armani%20-%20Acqua%20di%20Gi%C3%B2%20Eau%20de%20Parfum",
    "category": "Aquatic",
    "occasion": "Daily / Summer",
    "notes": "marine notes, citrus, woods"
  },
  {
    "name": "Cedrat Boise",
    "house": "Designer",
    "inspiration": "Mancera - Cedrat Boise",
    "status": "In stock",
    "emojis": "🍋🖤🪵",
    "p3": "$7",
    "p5": "$11",
    "p10": "$15",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Mancera%20-%20Cedrat%20Boise",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Grand Soir",
    "house": "Designer",
    "inspiration": "MFK - Grand Soir",
    "status": "In stock",
    "emojis": "🌌🔥🍯",
    "p3": "$18",
    "p5": "$40",
    "p10": "$65",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=MFK%20-%20Grand%20Soir",
    "category": "Amber",
    "occasion": "Date / Autumn",
    "notes": "amber, vanilla, benzoin"
  },
  {
    "name": "1 Million - Royal",
    "house": "Designer",
    "inspiration": "Paco Rabanne - 1M Royal",
    "status": "In stock",
    "emojis": "🏰🌿🌌",
    "p3": "$8",
    "p5": "$18",
    "p10": "$30",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Paco%20Rabanne%20-%201M%20Royal",
    "category": "Sweet / Aromatic",
    "occasion": "Date / Autumn",
    "notes": "lavender, woods, sweetness"
  },
  {
    "name": "Polo 67 EDP",
    "house": "Designer",
    "inspiration": "Ralph Lauren - Polo 67",
    "status": "In stock",
    "emojis": "🍍🌿🪵",
    "p3": "$6",
    "p5": "$14",
    "p10": "$20",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Ralph%20Lauren%20-%20Polo%2067",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Spicebomb Metallic Musk",
    "house": "Designer",
    "inspiration": "Viktor&Rolf - SpiceBomb Metallic Musk",
    "status": "In stock",
    "emojis": "🧊🧥💿",
    "p3": "$8",
    "p5": "$13",
    "p10": "$22",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Viktor%26Rolf%20-%20SpiceBomb%20Metallic%20Musk",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Spicebomb Infrared EDP",
    "house": "Designer",
    "inspiration": "Viktor&Rolf - SpiceBomb Infrared",
    "status": "In stock",
    "emojis": "🌶🔥🍬",
    "p3": "$8",
    "p5": "$13",
    "p10": "$22",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Viktor%26Rolf%20-%20SpiceBomb%20Infrared",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Born in Roma Coral Fantasy EDT",
    "house": "Designer",
    "inspiration": "Valentino - Born in Roma Coral Fantasy",
    "status": "In stock",
    "emojis": "🍎🌿🎩",
    "p3": "$8",
    "p5": "$17",
    "p10": "$30",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Valentino%20-%20Born%20in%20Roma%20Coral%20Fantasy",
    "category": "Fruity Sweet",
    "occasion": "Date / Autumn",
    "notes": "apple, woods, amber sweetness"
  },
  {
    "name": "XJ 1861 Naxos",
    "house": "Designer",
    "inspiration": "Xerjoff - Naxos",
    "status": "In stock",
    "emojis": "🍯🍊🍂",
    "p3": "$14",
    "p5": "$27",
    "p10": "$50",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Xerjoff%20-%20Naxos",
    "category": "Honey Tobacco",
    "occasion": "Date / Autumn",
    "notes": "honey, citrus, tobacco, vanilla"
  },
  {
    "name": "Royal Taboo Extrait",
    "house": "French Avenue",
    "inspiration": "Creed - Centaurus",
    "status": "In stock",
    "emojis": "👑🕰🌿",
    "p3": "$4",
    "p5": "$7",
    "p10": "$10",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Aromatix-X-French-Avenue/Royal-Taboo-99330.html",
    "category": "Spicy Amber",
    "occasion": "Date / Autumn",
    "notes": "spice, tobacco nuance, woods"
  },
  {
    "name": "Teas Me Extrait",
    "house": "French Avenue",
    "inspiration": "Nishane - Wulóng Chá",
    "status": "In stock",
    "emojis": "🍋🍵✨",
    "p3": "$4",
    "p5": "$7",
    "p10": "$10",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Aromatix-X-French-Avenue/Teas-Me-117532.html",
    "category": "Tea Fresh",
    "occasion": "Daily / Summer",
    "notes": "citrus, tea, clean musk"
  },
  {
    "name": "Lumière Garçon",
    "house": "French Avenue",
    "inspiration": "D&G - The One Luminous Night",
    "status": "In stock",
    "emojis": "🌙🌴🧂",
    "p3": "$4",
    "p5": "$6",
    "p10": "$11",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/French-Avenue/Lumiere-Garcon-94712.html",
    "category": "Fragrance",
    "occasion": "Date / Autumn",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Obsidian",
    "house": "French Avenue",
    "inspiration": "By Kilian - Angels Share on the Rocks",
    "status": "In stock",
    "emojis": "🧊🍊🥃",
    "p3": "$6",
    "p5": "$9",
    "p10": "$14",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/French-Avenue/Obsidian-120872.html,
    "category": "Boozy Sweet",
    "occasion": "Date / Autumn",
    "notes": "cognac, spice, oak, vanilla warmth"
  },
  {
    "name": "Moonstone Bleu",
    "house": "French Avenue",
    "inspiration": "Penhaligons - Sartorial",
    "status": "In stock",
    "emojis": "💎🌊🧼",
    "p3": "$4",
    "p5": "$8",
    "p10": "$10",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/French-Avenue/Moonstone-Bleu-100011.html",
    "category": "Clean / Aromatic",
    "occasion": "Daily / Versatile",
    "notes": "metallic fresh, lavender, woods"
  },
  {
    "name": "Mexican Tobacco Extrait",
    "house": "Ibraheem AlQurashi",
    "inspiration": "Jeroboam - Gozo",
    "status": "In stock",
    "emojis": "🍫🌹🔥",
    "p3": "$10",
    "p5": "N/A",
    "p10": "N/A",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Ibraheem-AlQurashi/Mexican-Tobacco-100563.html",
    "category": "Tobacco",
    "occasion": "Date / Autumn",
    "notes": "tobacco, warmth, spice"
  },
  {
    "name": "Jamaican Tobacco Extrait",
    "house": "Ibraheem AlQurashi",
    "inspiration": "Ex Nihilo - Brompton Immortals Extrait",
    "status": "In stock",
    "emojis": "🌿🪵🌫",
    "p3": "$10",
    "p5": "N/A",
    "p10": "N/A",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Ibraheem-AlQurashi/Jamaican-Tobacco-100564.html",
    "category": "Tobacco",
    "occasion": "Date / Autumn",
    "notes": "tobacco, warmth, spice"
  },
  {
    "name": "Cuban Tobacco Extrait",
    "house": "Ibraheem AlQurashi",
    "inspiration": "Le Labo - Tabac 28",
    "status": "In stock",
    "emojis": "🍯🍫🥃",
    "p3": "$10",
    "p5": "N/A",
    "p10": "N/A",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Le%20Labo%20-%20Tabac%2028",
    "category": "Tobacco",
    "occasion": "Date / Autumn",
    "notes": "tobacco, warmth, spice"
  },
  {
    "name": "Greek Tobacco Extrait",
    "house": "Ibraheem AlQurashi",
    "inspiration": "Ex Nihilo - Fleur Narcotique",
    "status": "In stock",
    "emojis": "🌸🍑🌹",
    "p3": "$8",
    "p5": "$13",
    "p10": "$22",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Ibraheem-AlQurashi/Greek-Tobacco-100553.html",
    "category": "Tobacco",
    "occasion": "Date / Autumn",
    "notes": "tobacco, warmth, spice"
  },
  {
    "name": "Spanish Tobacco Extrait",
    "house": "Ibraheem AlQurashi",
    "inspiration": "Orto Parisi - Megamare",
    "status": "In stock",
    "emojis": "🌊🪵🫧",
    "p3": "$10",
    "p5": "N/A",
    "p10": "N/A",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Ibraheem-AlQurashi/Spanish-Tobacco-100551.html",
    "category": "Tobacco",
    "occasion": "Date / Autumn",
    "notes": "tobacco, warmth, spice"
  },
  {
    "name": "French Tobacco Extrait",
    "house": "Ibraheem AlQurashi",
    "inspiration": "Louis Vuitton - Imagination",
    "status": "In stock",
    "emojis": "🍊🍃🧼",
    "p3": "$10",
    "p5": "N/A",
    "p10": "N/A",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Ibraheem-AlQurashi/French-Tobacco-100552.html",
    "category": "Tobacco",
    "occasion": "Date / Autumn",
    "notes": "tobacco, warmth, spice"
  },
  {
    "name": "Brazillian Tobacco Extrait",
    "house": "Ibraheem AlQurashi",
    "inspiration": "Parfums de Marly - Haltane",
    "status": "In stock",
    "emojis": "🌶🍒🧥",
    "p3": "$10",
    "p5": "N/A",
    "p10": "N/A",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Ibraheem-AlQurashi/Brazilian-Tobacco-100562.html",
    "category": "Tobacco",
    "occasion": "Date / Autumn",
    "notes": "tobacco, warmth, spice"
  },
  {
    "name": "Tonka Powder",
    "house": "Jalu",
    "inspiration": "Hybrid - A Tonka/V Powder",
    "status": "In stock",
    "emojis": "🧁✨🕯",
    "p3": "$6",
    "p5": "$11",
    "p10": "$15",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Montale/Arabians-Tonka-57384.html",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Triumvrate",
    "house": "Jalu",
    "inspiration": "Hybrid - MYSLF/Y + Bubblegum",
    "status": "In stock",
    "emojis": "🍬🌿🍋",
    "p3": "$6",
    "p5": "$11",
    "p10": "$15",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Yves-Saint-Laurent/MYSLF-Eau-de-Parfum-84094.html",
    "category": "Fresh Sweet",
    "occasion": "Daily / Summer",
    "notes": "fresh citrus, florals, bubblegum sweetness"
  },
  {
    "name": "Purple Haze",
    "house": "Jalu",
    "inspiration": "Hybrid - Erba Pura/Rouge Trafalgar",
    "status": "In stock",
    "emojis": "🍊🌸🌿",
    "p3": "$6",
    "p5": "$11",
    "p10": "$15",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Dior/Rouge-Trafalgar-58665.html",
    "category": "Fruity Sweet",
    "occasion": "Date / Autumn",
    "notes": "citrus, fruit, musk, amber"
  },
  {
    "name": "Jaguar",
    "house": "Jalu",
    "inspiration": "Hybrid - L'Immensite/Tygar",
    "status": "In stock",
    "emojis": "🫚🐅🍊",
    "p3": "$6",
    "p5": "$11",
    "p10": "$15",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Bvlgari/Tygar-41222.html",
    "category": "Ginger Citrus",
    "occasion": "Daily / Summer",
    "notes": "ginger, grapefruit, amber woods"
  },
  {
    "name": "Nirvana",
    "house": "Jalu",
    "inspiration": "Roja - Elysium Pour Homme Parfum",
    "status": "In stock",
    "emojis": "🍋🌿✨",
    "p3": "$6",
    "p5": "$11",
    "p10": "$15",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Roja-Dove/Elysium-Pour-Homme-Parfum-Cologne-46296.html",
    "category": "Iris / Leather",
    "occasion": "Date / Autumn",
    "notes": "iris, amber, woods, leather nuance"
  },
  {
    "name": "SANAYA",
    "house": "Junaid",
    "inspiration": "LV - Imagination",
    "status": "In stock",
    "emojis": "🫧🧊🌿",
    "p3": "$6",
    "p5": "$11",
    "p10": "$18",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=LV%20-%20Imagination",
    "category": "Citrus Tea",
    "occasion": "Daily / Summer",
    "notes": "citrus, ginger, tea, clean amber"
  },
  {
    "name": "Emeer",
    "house": "Lattafa",
    "inspiration": "Clive Christian - Town & Country",
    "status": "In stock",
    "emojis": "🍋🌿🪵",
    "p3": "$4",
    "p5": "$6",
    "p10": "$9",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Emeer-89761.html",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Masa",
    "house": "Lattafa",
    "inspiration": "Marc-Antoine Barrois - Ganymede",
    "status": "In stock",
    "emojis": "🪨✨🍊",
    "p3": "$6",
    "p5": "$10",
    "p10": "$15",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Masa-88636.html",
    "category": "Mineral Woods",
    "occasion": "Daily / Versatile",
    "notes": "mineral citrus, suede-like woods"
  },
  {
    "name": "Musamam Black Intense",
    "house": "Lattafa",
    "inspiration": "Unique",
    "status": "In stock",
    "emojis": "🖤🌲🍫",
    "p3": "$8",
    "p5": "$14",
    "p10": "$23",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Lattafa%20Musamam%20Black%20Intense",
    "category": "Woody Sweet",
    "occasion": "Date / Autumn",
    "notes": "woody spice, tonka, maple sweetness"
  },
  {
    "name": "Opulent Dubai",
    "house": "Lattafa",
    "inspiration": "SHL - God of Fire",
    "status": "In stock",
    "emojis": "🌴🥭✨",
    "p3": "$5",
    "p5": "$8",
    "p10": "$14",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Opulent-Dubai-105609.html",
    "category": "Tropical Fruity",
    "occasion": "Daily / Versatile",
    "notes": "mango, citrus, ginger, amber woods"
  },
  {
    "name": "Atlas",
    "house": "Lattafa",
    "inspiration": "Orto Parisi - Megamare",
    "status": "In stock",
    "emojis": "🌊⚪🫧",
    "p3": "$7",
    "p5": "$11",
    "p10": "$14",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Atlas-89765.html",
    "category": "Marine / Powerful",
    "occasion": "Daily / Summer",
    "notes": "marine, salty woods, musky amber"
  },
  {
    "name": "Jasoor",
    "house": "Lattafa",
    "inspiration": "Valentino - Born in Roma Coral Fantasy",
    "status": "In stock",
    "emojis": "🍎🍂🪵",
    "p3": "$6",
    "p5": "$8",
    "p10": "$11",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Jasoor-85093.html",
    "category": "Fruity Sweet",
    "occasion": "Date / Autumn",
    "notes": "apple, woods, amber sweetness"
  },
  {
    "name": "Vintage Radio",
    "house": "Lattafa",
    "inspiration": "Initio Parfums Prives - Paragon",
    "status": "In stock",
    "emojis": "📻🍇🌲",
    "p3": "$6",
    "p5": "$8",
    "p10": "$12",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Vintage-Radio-89454.html",
    "category": "Fruity Woody",
    "occasion": "Daily / Versatile",
    "notes": "plum, sage, palo santo, woods"
  },
  {
    "name": "Art of Nature II",
    "house": "Lattafa",
    "inspiration": "Parfums de Marly - Althaïr",
    "status": "In stock",
    "emojis": "🍊🍦🎩",
    "p3": "$4",
    "p5": "$6",
    "p10": "$9",
    "fragranticaUrl": "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Art-Of-Nature-II-98242.html",
    "category": "Vanilla / Sweet",
    "occasion": "Date / Autumn",
    "notes": "vanilla, citrus, amber woods"
  },
  {
    "name": "Teriaq Intense",
    "house": "Lattafa",
    "inspiration": "Unique",
    "status": "In stock",
    "emojis": "🥃🕯🌌",
    "p3": "$6",
    "p5": "$11",
    "p10": "$15",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Lattafa%20Teriaq%20Intense",
    "category": "Amber / Night",
    "occasion": "Date / Autumn",
    "notes": "boozy amber, spice, dark warmth"
  },
  {
    "name": "Ana Abiyedh - Rouge (W)",
    "house": "Lattafa",
    "inspiration": "MFK - Baccarat Rouge 540",
    "status": "In stock",
    "emojis": "🍐🍬✨",
    "p3": "$5",
    "p5": "$7",
    "p10": "$12",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=MFK%20-%20Baccarat%20Rouge%20540",
    "category": "Sweet Amber",
    "occasion": "Date / Autumn",
    "notes": "airy amber, sweet musk"
  },
  {
    "name": "Luxe Street",
    "house": "Maison Alhambra",
    "inspiration": "Bond No.9 - Lafayette St.",
    "status": "In stock",
    "emojis": "🪻🍎🗽",
    "p3": "$5",
    "p5": "$7",
    "p10": "$12",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bond%20No.9%20-%20Lafayette%20St.",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Luxe Chic (W)",
    "house": "Maison Alhambra",
    "inspiration": "Bond No.9 - Nolita",
    "status": "In stock",
    "emojis": "🌸💄🍓",
    "p3": "$5",
    "p5": "$7",
    "p10": "$12",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Bond%20No.9%20-%20Nolita",
    "category": "Fragrance",
    "occasion": "Daily / Versatile",
    "notes": "designer and niche-inspired fragrance profile"
  },
  {
    "name": "Winsome",
    "house": "Maison Alhambra",
    "inspiration": "Yves Saint Laurent - Tuxedo",
    "status": "In stock",
    "emojis": "🖤🧥🥂",
    "p3": "$6",
    "p5": "$8",
    "p10": "$11",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Yves%20Saint%20Laurent%20-%20Tuxedo",
    "category": "Amber / Dressy",
    "occasion": "Date / Autumn",
    "notes": "patchouli, amber, rose, vanilla"
  },
  {
    "name": "Legacy",
    "house": "Maison Asrar",
    "inspiration": "Ex Nihilo - Blue Talisman",
    "status": "In stock",
    "emojis": "🍐✨🌿",
    "p3": "$6",
    "p5": "$9",
    "p10": "$14",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Ex%20Nihilo%20-%20Blue%20Talisman",
    "category": "Fruity Fresh",
    "occasion": "Daily / Summer",
    "notes": "pear, ginger, orange blossom, musk"
  },
  {
    "name": "Rifaqaat",
    "house": "Paris Corner",
    "inspiration": "Yves Saint Laurent - Babycat",
    "status": "In stock",
    "emojis": "🐆🍦🔥",
    "p3": "$5",
    "p5": "$7",
    "p10": "$12",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Yves%20Saint%20Laurent%20-%20Babycat",
    "category": "Vanilla Amber",
    "occasion": "Date / Autumn",
    "notes": "vanilla, resin, suede-like warmth"
  },
  {
    "name": "Tiger [Cal Cologne]",
    "house": "Rayhaan",
    "inspiration": "Penhaligon's - Halfeti",
    "status": "In stock",
    "emojis": "🐅🌶🌹",
    "p3": "$6",
    "p5": "$10",
    "p10": "$15",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Penhaligon%27s%20-%20Halfeti",
    "category": "Spicy Rose",
    "occasion": "Daily / Versatile",
    "notes": "rose, spice, woods, amber"
  },
  {
    "name": "Seasons Drift",
    "house": "Riffs",
    "inspiration": "Chanel - Bleu de Chanel L’Exclusif",
    "status": "In stock",
    "emojis": "🌊🌲🖤",
    "p3": "$6",
    "p5": "$10",
    "p10": "$15",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Chanel%20-%20Bleu%20de%20Chanel%20L%E2%80%99Exclusif",
    "category": "Blue / Woody",
    "occasion": "Daily / Summer",
    "notes": "citrus, woods, amber, incense"
  },
  {
    "name": "Cardamom and Apple",
    "house": "Swiss Arabian",
    "inspiration": "Armani - Code Profumo",
    "status": "In stock",
    "emojis": "🍏🌿✨",
    "p3": "$6",
    "p5": "$11",
    "p10": "$18",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Armani%20-%20Code%20Profumo",
    "category": "Aquatic Incense",
    "occasion": "Daily / Summer",
    "notes": "marine notes, incense, woods"
  },
  {
    "name": "Incense 01 Extrait",
    "house": "Swiss Arabian",
    "inspiration": "Original Creation",
    "status": "In stock",
    "emojis": "🕯🌰💨",
    "p3": "$10",
    "p5": "$20",
    "p10": "$30",
    "fragranticaUrl": "https://www.fragrantica.com/search/?query=Swiss%20Arabian%20Incense%2001%20Extrait",
    "category": "Incense Gourmand",
    "occasion": "Date / Autumn",
    "notes": "incense, nutty sweetness, woods"
  }
];

const packs = [
  {
    "name": "Night Out Pack",
    "emojis": "🌙🔥🥃",
    "price": "3 x 3mL — $15",
    "items": [
      "9PM - Night Out Extrait",
      "Spicebomb Infrared EDP",
      "Booz Extreme"
    ],
    "desc": "Sweet, loud and built for dates, drinks and going out."
  },
  {
    "name": "Clean Luxury Pack",
    "emojis": "🤍🍋✨",
    "price": "3 x 3mL — $18",
    "items": [
      "SANAYA",
      "Nirvana",
      "Iris Infinite Extrait"
    ],
    "desc": "Fresh, clean and expensive-smelling."
  },
  {
    "name": "Tropical Pack",
    "emojis": "🥭🍍🍋",
    "price": "3 x 3mL — $15",
    "items": [
      "Opulent Dubai",
      "Supremacy Collectors Ed.",
      "SANAYA"
    ],
    "desc": "Bright fruity warm-weather scents."
  },
  {
    "name": "Arabian Power Pack",
    "emojis": "🐎🖤🔥",
    "price": "3 x 3mL — $20",
    "items": [
      "Wild Colt",
      "Musamam Black Intense",
      "Ignite Oud Extrait"
    ],
    "desc": "Strong Middle Eastern-style performers."
  },
  {
    "name": "Office Boss Pack",
    "emojis": "💼🌲🧼",
    "price": "3 x 3mL — $18",
    "items": [
      "Seasons Drift",
      "Boss Bottled Parfum",
      "Masa"
    ],
    "desc": "Polished daily scents for work, meetings and smart casual wear."
  },
  {
    "name": "Sweet Starter Pack",
    "emojis": "🍬✨🥃",
    "price": "3 x 3mL — $15",
    "items": [
      "Ana Abiyedh - Rouge (W)",
      "Booz",
      "Art of Nature II"
    ],
    "desc": "Sweet, easy and compliment-focused."
  }
];
