(()=>{'use strict';
const $=id=>document.getElementById(id),norm=v=>String(v||'').toLowerCase().trim(),num=v=>Number(String(v||'').replace(/[^0-9.]/g,''))||0,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={settings:null,catalogue:[]};
function endpoint(action,params={}){const base=state.settings.adminWriteEndpoint,u=new URL(base);u.searchParams.set('action',action);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));u.searchParams.set('t',Date.now());return u.toString()}
async function get(action,params){const r=await fetch(endpoint(action,params),{cache:'no-store'}),j=await r.json();if(j.ok===false)throw Error(j.error||'Request failed');return j}
function toks(v){return [...new Set(norm(v).replace(/[^a-z0-9]+/g,' ').split(/\s+/).filter(x=>x.length>2))]}
function overlap(a,b){const A=toks(a),B=new Set(toks(b));return A.length?A.filter(x=>B.has(x)).length/A.length:0}
const niche=['mancera','montale','xerjoff','goldfield','essential parfums','nishane','amouage','gissah','parfums de marly','creed','initio','memo paris','maison francis kurkdjian','byredo','le labo','diptyque','penhaligons','roja','clive christian','nasomatto','ortho parisi'];
const designer=['armani','giorgio armani','dior','hugo boss','issey miyake','azzaro','valentino','versace','dolce','gabbana','rabanne','paco rabanne','givenchy','gucci','burberry','coach','calvin klein','ralph lauren','montblanc','davidoff','tommy hilfiger','marc jacobs','jean paul gaultier','ysl','yves saint laurent','hermes','chanel','prada','mugler','lacoste','bentley','jimmy choo','moschino','narciso rodriguez'];
function classify(x){const t=norm((x.house||'')+' '+x.name);if(niche.some(v=>t.includes(v)))return'Niche';if(designer.some(v=>t.includes(v)))return'Designer';if(x.category&&x.category!=='Any')return x.category;return'Middle Eastern'}
function inferStyle(x){const t=norm([x.name,x.inspiredBy,x.tags,x.description].join(' '));if(/vanilla|tonka|marshmallow|gourmand|choco|chocolate|sugar|caramel|coffee|pistachio/.test(t))return'Vanilla / Gourmand';if(/aqua|sea|marine|blue|citrus|bergamot|fresh|ice|chill|aquatic|neroli/.test(t))return'Fresh / Aquatic';if(/tobacco|smoke|oud|leather|amber|spice|wood|sandal/.test(t))return'Woody / Spicy';if(/rose|floral|flower|jasmine|tuberose|iris/.test(t))return'Floral';if(/fruit|mango|apple|peach|berry|cherry|pineapple/.test(t))return'Fruity';return'Unclassified'}
function score(x,goal){const names=state.catalogue.map(c=>`${c.House||''} ${c.Fragrance||''} ${c['Inspired By']||c['Inspired by']||''}`),candidate=`${x.house||''} ${x.name||''} ${x.inspiredBy||''}`;const max=Math.max(0,...names.map(n=>overlap(candidate,n)));const houseCount=state.catalogue.filter(c=>norm(c.House)===norm(x.house)&&norm(x.house)).length;const style=inferStyle(x),styleKey=norm(style.split(' / ')[0]),styleCount=state.catalogue.filter(c=>norm(c['Scent Style']).includes(styleKey)).length;const uniqueness=Math.max(0,Math.round((1-max)*30));const gap=Math.max(3,30-Math.min(27,styleCount*3+Math.min(houseCount,5)));const perMl=x.sizeMl?x.bestPrice/x.sizeMl:x.bestPrice/100;const value=Math.max(3,Math.min(20,Math.round(21-perMl*18)));const pack=style==='Unclassified'?5:Math.max(5,10-Math.min(5,styleCount));const priceBonus=x.offerCount>1?Math.min(5,x.offerCount-1):0;let total=gap+uniqueness+value+pack+priceBonus;if(goal==='different')total+=Math.round(uniqueness*.25);if(goal==='value')total+=Math.round(value*.35)+priceBonus;if(goal==='packs')total+=pack;total=Math.min(97,Math.round(total));return{total,gap,uniqueness,value,pack,max,style,houseCount,priceBonus}}
function money(v){return new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:2}).format(v||0)}
function selectedRetailers(){return [...document.querySelectorAll('input[name=scoutRetailer]:checked')].map(x=>x.value)}
function renderHealth(statuses=[]){const box=$('scoutSourceHealth');box.hidden=false;box.innerHTML=statuses.map(s=>`<span class="source-pill ${s.ok?'ok':'warn'}"><b>${esc(s.label||s.source)}</b> ${s.ok?`${s.count||0} found`:`unavailable`}</span>`).join('')}
function offersHtml(x){if(!x.offers||x.offers.length<2)return'';return `<details class="scout-offers"><summary>Compare ${x.offers.length} retailer prices</summary>${x.offers.map((o,i)=>`<a href="${esc(o.url)}" target="_blank" rel="noopener"><span>${i===0?'Best · ':''}${esc(o.source)}</span><b>${money(o.price)}</b>${o.available===false?'<em>Sold out</em>':''}</a>`).join('')}</details>`}
function render(items,meta={}){const goal=$('scoutGoal').value,cat=$('scoutCategory').value;items=items.map(x=>({...x,category:classify(x)}));if(cat!=='Any')items=items.filter(x=>x.category===cat);items=items.map(x=>({...x,s:score(x,goal)})).sort((a,b)=>b.s.total-a.s.total||a.bestPrice-b.bestPrice).slice(0,15);$('scoutSummary').hidden=false;$('scoutSummary').innerHTML=`<article><span>Unique candidates</span><strong>${items.length}</strong></article><article><span>Best fit</span><strong>${items[0]?items[0].s.total+'/100':'—'}</strong></article><article><span>Retailer offers</span><strong>${meta.rawCount||0}</strong></article><article><span>Budget</span><strong>${esc($('scoutBudget').selectedOptions[0].text)}</strong></article>`;
$('scoutResults').innerHTML=items.length?items.map((x,i)=>`<article class="scout-card"><div class="scout-rank">#${i+1}</div><div class="scout-card-head"><div><p class="eyebrow">${esc(x.bestSource)} · ${esc(x.category)}</p><h3>${esc(x.name)}</h3><p class="muted">${esc(x.house||'')} ${x.inspiredBy?`· Inspired by ${esc(x.inspiredBy)}`:''}</p></div><div class="scout-score"><strong>${x.s.total}</strong><span>/100</span></div></div><div class="scout-best-price"><div><span>Best current price</span><strong>${money(x.bestPrice)}</strong><small>${x.size?esc(x.size):''}</small></div>${x.offerCount>1?`<div class="price-save"><span>${x.offerCount} stores</span>${x.highestPrice>x.bestPrice?`<b>Save ${money(x.highestPrice-x.bestPrice)}</b>`:''}</div>`:''}</div><div class="scout-reasons"><span>Gap <b>${x.s.gap}/30</b></span><span>Uniqueness <b>${x.s.uniqueness}/30</b></span><span>Value <b>${x.s.value}/20</b></span><span>Pack fit <b>${x.s.pack}/10</b></span></div><p class="scout-why">${x.s.max>.55?'⚠ Close catalogue overlap detected.':'✓ Relatively different from your current catalogue.'} ${x.s.houseCount>3?'You already carry several bottles from this house.':'House duplication is low.'} Inferred profile: ${esc(x.s.style)}.${x.offerCount>1?' Multiple retailers matched this bottle, so the score uses the cheapest listing.':''}</p>${offersHtml(x)}<div class="scout-actions"><a class="button primary" href="${esc(x.bestUrl)}" target="_blank" rel="noopener">View best price</a><button class="button" data-analyse="${i}">Analyse deeper</button></div></article>`).join(''):'<div class="admin-panel empty">No matching in-stock candidates were returned in this price band/category. Try another category, retailer, or turn off “In stock only”.</div>';window._scoutItems=items}
async function run(){const retailers=selectedRetailers();if(!retailers.length){$('scoutStatus').textContent='Select at least one retailer.';return}const [min,max]=$('scoutBudget').value.split('-');$('scoutRun').disabled=true;$('scoutStatus').textContent='Scanning retailers, merging duplicate bottles and comparing against your collection…';$('scoutResults').innerHTML='<div class="admin-panel empty">Searching live retailer catalogues…</div>';try{const j=await get('buyScout',{min,max,category:$('scoutCategory').value,sources:retailers.join(','),inStock:$('scoutInStock').checked?'1':'0'});renderHealth(j.sources||[]);render(j.items||[],{rawCount:j.rawCount||0});$('scoutStatus').textContent=`Ready · ${j.items?.length||0} unique candidates · ${j.rawCount||0} retailer offers · compared with ${state.catalogue.length} catalogue bottles`;}catch(e){$('scoutStatus').textContent='Buy Scout could not complete: '+e.message;$('scoutResults').innerHTML='<div class="admin-panel empty">Check that the V3.2 Apps Script Code.gs has been deployed as a new web-app version.</div>'}finally{$('scoutRun').disabled=false}}
$('scoutRun').addEventListener('click',run);$('scoutResults').addEventListener('click',e=>{const n=e.target.dataset.analyse;if(n===undefined)return;const x=window._scoutItems[Number(n)];sessionStorage.setItem('deadendScoutPrefill',JSON.stringify({name:x.name,house:x.house,collection:x.category,cost:x.bestPrice,size:x.sizeMl||num(x.size)||100,notes:[x.inspiredBy?'Inspired by '+x.inspiredBy:'',`Best price ${money(x.bestPrice)} at ${x.bestSource}`,x.offerCount>1?`${x.offerCount} retailer offers found`:'' ].filter(Boolean).join(' · '),url:x.bestUrl}));location.href='intelligence.html?source=scout'});$('amazonLink').href='https://www.amazon.com.au/s?k=mens+fragrance+perfume';
(async()=>{try{state.settings=await fetch('../settings.json',{cache:'no-store'}).then(r=>r.json());const j=await get('catalogue');state.catalogue=j.items||j||[];$('scoutStatus').textContent=`Ready · ${state.catalogue.length} catalogue bottles loaded. Choose a budget and search.`}catch(e){$('scoutStatus').textContent='Could not load catalogue: '+e.message}})();})();