(function(){
  const $=(id)=>document.getElementById(id); const state={settings:null,items:[]};
  function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
  function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;continue;}if(c==='"'){q=!q;continue;}if(c===','&&!q){row.push(cell);cell='';continue;}if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(v=>String(v).trim()!==''))rows.push(row);row=[];continue;}cell+=c;}row.push(cell);if(row.some(v=>String(v).trim()!==''))rows.push(row);if(!rows.length)return[];const h=rows.shift().map(x=>x.trim());return rows.map(r=>Object.fromEntries(h.map((x,i)=>[x,(r[i]||'').trim()])));} 
  function name(i){return [i.House,i.Fragrance].filter(Boolean).join(' · ') || i.ID || 'Untitled';}
  function bool(v){return ['true','yes','1','y'].includes(String(v||'').toLowerCase());}
  function today(offset=0){const d=new Date();d.setDate(d.getDate()+offset);return d.toISOString().slice(0,10);}
  async function load(){state.settings=await fetch('../settings.json',{cache:'no-store'}).then(r=>r.json());let items=[];try{const res=await fetch(state.settings.catalogueCsvUrl,{cache:'no-store'});if(res.ok)items=parseCSV(await res.text());}catch(e){}state.items=items.filter(i=>(i.Status||'').toLowerCase()!=='hidden');render();}
  function render(){ $('featuredStart').value ||= today(0); $('featuredEnd').value ||= today(Number(state.settings.weeklyDiscountDays||7)); $('featuredDiscount').value = state.settings.weeklyDiscountPercent || 20; $('featuredSelect').innerHTML=state.items.map(i=>`<option value="${esc(i.ID)}" ${bool(i.Featured)?'selected':''}>${esc(name(i))}</option>`).join(''); renderStaff(); }
  function renderStaff(){const q=$('staffSearch').value.toLowerCase().trim();const items=state.items.filter(i=>!q||name(i).toLowerCase().includes(q)||String(i.ID).toLowerCase().includes(q)).slice(0,120);$('staffList').innerHTML=items.map(i=>`<label class="check-row"><input type="checkbox" value="${esc(i.ID)}" ${bool(i['Staff Pick'])?'checked':''}><span><strong>${esc(name(i))}</strong><em>${esc(i.Collection||'')} · ${esc(i.ID||'')}</em></span></label>`).join('') || '<div class="empty">No bottles found.</div>';}
  async function saveFeatured(){const id=$('featuredSelect').value;if(!id)return;$('featuredStatus').textContent='Saving...';const payload={action:'setFeatured',id,discount:$('featuredDiscount').value,startDate:$('featuredStart').value,endDate:$('featuredEnd').value};try{await DeadEndAdminWrite.submit(state.settings.adminWriteEndpoint,payload);$('featuredStatus').textContent='Saved. Refresh the public site after Google Sheets updates.';}catch(e){$('featuredStatus').textContent='Save failed: '+e.message;}}
  async function saveStaff(){const ids=[...document.querySelectorAll('#staffList input:checked')].map(i=>i.value);$('staffStatus').textContent='Saving...';const payload={action:'setStaffPicks',ids};try{await DeadEndAdminWrite.submit(state.settings.adminWriteEndpoint,payload);$('staffStatus').textContent='Saved '+ids.length+' staff picks.';}catch(e){$('staffStatus').textContent='Save failed: '+e.message;}}
  $('staffSearch').addEventListener('input',renderStaff);$('saveFeatured').addEventListener('click',saveFeatured);$('saveStaff').addEventListener('click',saveStaff);load();
})();
