(function(){
  const $ = (id) => document.getElementById(id);
  const state = { settings:null, items:[], selected:null };
  const fieldNames = {
    currentMl:['Current mL','Current Amount Left (mL)','Current Amount Left','Amount Left','Amount Left mL','Remaining mL'],
    bottleSize:['Bottle Size (mL)','Bottle Size','Size mL'],
    purchasePrice:['Purchase Price','Purchase Cost','Cost'],
    normalRrp:['Normal RRP','RRP','Retail Price'],
    description:['Description','Short Description']
  };
  function escapeHtml(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
  function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;continue;}if(c==='"'){q=!q;continue;}if(c===','&&!q){row.push(cell);cell='';continue;}if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(v=>String(v).trim()!==''))rows.push(row);row=[];continue;}cell+=c;}row.push(cell);if(row.some(v=>String(v).trim()!==''))rows.push(row);if(!rows.length)return[];const h=rows.shift().map(x=>x.trim());return rows.map(r=>Object.fromEntries(h.map((x,i)=>[x,(r[i]||'').trim()])));} 
  function first(item, names){for(const n of names){if(item[n]!==undefined && item[n]!==null && String(item[n]).trim()!=='') return item[n];}return '';}
  function displayName(item){return [item.House,item.Fragrance].filter(Boolean).join(' · ') || item.ID || 'Untitled';}
  async function loadSettings(){state.settings=await fetch('../settings.json',{cache:'no-store'}).then(r=>r.json());}
  async function loadCatalogue(){let items=[];try{const res=await fetch(state.settings.catalogueCsvUrl,{cache:'no-store'});if(res.ok)items=parseCSV(await res.text());}catch(e){} if(!items.length){try{const fb=await fetch('../catalogue-fallback.json',{cache:'no-store'}).then(r=>r.json());items=fb.items||[];}catch(e){}} state.items=items; renderFilters(); renderList();}
  function renderFilters(){const values=[...new Set(state.items.map(i=>i.Collection).filter(Boolean))].sort();$('collectionFilter').innerHTML='<option value="">All</option>'+values.map(v=>`<option>${escapeHtml(v)}</option>`).join('');}
  function filtered(){const q=$('search').value.trim().toLowerCase();const col=$('collectionFilter').value;return state.items.filter(item=>{const hay=[item.ID,item.House,item.Fragrance,item.Collection].join(' ').toLowerCase();return (!q||hay.includes(q))&&(!col||item.Collection===col);}).slice(0,80);}
  function renderList(){const rows=filtered();$('inventoryList').innerHTML=rows.map(item=>{const ml=first(item,fieldNames.currentMl);return `<button class="edit-row" type="button" data-id="${escapeHtml(item.ID)}"><strong>${escapeHtml(displayName(item))}</strong><span>${escapeHtml(item.Collection||'')} · ${escapeHtml(item.Status||'Status unknown')}</span><em>${ml?escapeHtml(ml)+'mL':'mL not set'}</em></button>`;}).join('') || '<div class="empty">No bottles found.</div>'; document.querySelectorAll('.edit-row').forEach(btn=>btn.addEventListener('click',()=>selectItem(btn.dataset.id)));}
  function selectItem(id){const item=state.items.find(i=>String(i.ID)===String(id));if(!item)return;state.selected=item;$('editId').value=item.ID||'';$('editTitle').textContent=displayName(item);$('editMeta').textContent=(item.ID||'')+' · '+(item.Collection||'');$('currentMl').value=first(item,fieldNames.currentMl);$('status').value=item.Status||'In Stock';$('price3').value=item['3mL']||'';$('price5').value=item['5mL']||'';$('price10').value=item['10mL']||'';$('bottleSize').value=first(item,fieldNames.bottleSize);$('purchasePrice').value=first(item,fieldNames.purchasePrice);$('normalRrp').value=first(item,fieldNames.normalRrp);$('description').value=first(item,fieldNames.description);$('saveStatus').textContent='';window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'});}
  async function save(e){e.preventDefault();if(!$('editId').value){$('saveStatus').textContent='Choose a bottle first.';return;}$('saveStatus').textContent='Saving...';const payload={action:'updateBottle',id:$('editId').value,fields:{'Current mL':$('currentMl').value,'Status':$('status').value,'3mL':$('price3').value,'5mL':$('price5').value,'10mL':$('price10').value,'Bottle Size (mL)':$('bottleSize').value,'Purchase Price':$('purchasePrice').value,'Normal RRP':$('normalRrp').value,'Description':$('description').value,'Last Updated':new Date().toISOString()}};try{await DeadEndAdminWrite.submit(state.settings.adminWriteEndpoint,payload);$('saveStatus').textContent='Saved. Give Google Sheets a few seconds, then reload to confirm.';}catch(err){$('saveStatus').textContent='Save failed: '+err.message;}}
  async function init(){await loadSettings();await loadCatalogue();$('search').addEventListener('input',renderList);$('collectionFilter').addEventListener('change',renderList);$('editForm').addEventListener('submit',save);$('reloadBtn').addEventListener('click',async()=>{await loadCatalogue();$('saveStatus').textContent='Reloaded.';});}
  init();
})();
