(function(){
 const $=id=>document.getElementById(id), state={settings:null,catalogue:[],cart:[],orders:[],items:[],editingId:null,messageLines:[]};
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const num=v=>Number(String(v??'').replace(/[^0-9.-]/g,''))||0,money=v=>'$'+num(v).toFixed(2),truth=v=>/^(true|1|yes)$/i.test(String(v||''));
 async function load(){state.settings=await fetch('../settings.json',{cache:'no-store'}).then(r=>r.json());resetForm();await Promise.all([loadCatalogue(),loadOrders(),loadItems()]);}
 async function get(action){const ep=state.settings.adminWriteEndpoint,u=ep+(ep.includes('?')?'&':'?')+'action='+encodeURIComponent(action)+'&t='+Date.now();return fetch(u,{cache:'no-store'}).then(r=>r.json())}
 async function loadCatalogue(){const d=await get('catalogue');state.catalogue=d.items||[]}
 async function loadOrders(){const d=await get('orders');state.orders=d.items||[];renderOrders()}
 async function loadItems(){const d=await get('orderItems');state.items=d.items||[]}
 function productName(i){return [i.House,i.Fragrance].filter(Boolean).join(' · ')} function price(i,s){return num(i[s+'mL'])}
 function searchProducts(){const q=$('productSearch').value.trim().toLowerCase();if(q.length<2){$('productResults').innerHTML='';return}const rows=state.catalogue.filter(i=>[i.ID,i.House,i.Fragrance].join(' ').toLowerCase().includes(q)).slice(0,12);$('productResults').innerHTML=rows.map(i=>`<article class="picker-card"><div><strong>${esc(productName(i))}</strong><small>${esc(i.Collection||'Catalogue')} · ${esc(i['Current mL']||i['Current Amount Left (mL)']||'—')}mL left</small></div><div class="size-actions">${[3,5,10].map(s=>`<button type="button" data-id="${esc(i.ID)}" data-size="${s}">${s}mL · ${money(price(i,s))}</button>`).join('')}</div></article>`).join('')||'<div class="empty">No matching fragrances.</div>';document.querySelectorAll('.size-actions button').forEach(b=>b.onclick=()=>addItem(b.dataset.id,num(b.dataset.size)))}
 function addItem(id,size){const p=state.catalogue.find(x=>String(x.ID)===String(id));if(!p)return;const ex=state.cart.find(x=>String(x.fragranceId)===String(id)&&x.sizeMl===size);if(ex)ex.quantity++;else state.cart.push({fragranceId:id,house:p.House||'',fragrance:p.Fragrance||'',sizeMl:size,quantity:1,priceEach:price(p,size)});renderCart();$('productSearch').value='';$('productResults').innerHTML=''}
 function renderCart(){if(!state.cart.length){$('orderItems').innerHTML='<div class="empty">Search and add a fragrance.</div>';calc();return}$('orderItems').innerHTML=state.cart.map((x,i)=>`<article class="order-line"><div><strong>${esc(x.house+' · '+x.fragrance)}</strong><small>${x.sizeMl}mL</small></div><label>Qty<input type="number" min="1" value="${x.quantity}" data-q="${i}"></label><label>Price<input type="number" min="0" step="0.01" value="${x.priceEach}" data-p="${i}"></label><strong>${money(x.quantity*x.priceEach)}</strong><button type="button" class="icon-button" data-r="${i}">×</button></article>`).join('');document.querySelectorAll('[data-q]').forEach(e=>e.oninput=()=>{state.cart[num(e.dataset.q)].quantity=Math.max(1,num(e.value));renderCart()});document.querySelectorAll('[data-p]').forEach(e=>e.oninput=()=>{state.cart[num(e.dataset.p)].priceEach=num(e.value);calc()});document.querySelectorAll('[data-r]').forEach(e=>e.onclick=()=>{state.cart.splice(num(e.dataset.r),1);renderCart()});calc()}
 function calc(){const subtotal=state.cart.reduce((a,x)=>a+x.quantity*x.priceEach,0);$('grandTotal').textContent=money(subtotal+num($('postage').value)-num($('discount').value))}
 function payload(){return {orderDate:$('orderDate').value,customer:$('customer').value.trim(),salesSource:$('salesSource').value,paymentStatus:$('paymentStatus').value,orderStatus:$('orderStatus').value,trackingNumber:$('trackingNumber').value.trim(),postage:num($('postage').value),discount:num($('discount').value),notes:$('notes').value.trim(),deductStock:$('deductStock').checked,items:state.cart}}
 const sleep=ms=>new Promise(r=>setTimeout(r,ms));
 function sameItems(orderId,expected){const actual=orderItems(orderId);if(actual.length!==expected.length)return false;return expected.every(e=>actual.some(a=>String(a['Fragrance ID']||'')===String(e.fragranceId||'')&&num(a['Size mL'])===num(e.sizeMl)&&num(a.Quantity)===num(e.quantity)&&Math.abs(num(a['Price Each'])-num(e.priceEach))<0.01))}
 async function refreshOrderData(){await Promise.all([loadOrders(),loadItems()])}
 async function waitForSavedOrder(editingId,expectedItems,previousIds,expectedStock,tries=18){for(let i=0;i<tries;i++){await sleep(700);await refreshOrderData();let id=editingId;if(!id){const created=state.orders.find(o=>!previousIds.has(o['Order ID']));id=created&&created['Order ID']}const order=id&&state.orders.find(o=>o['Order ID']===id);if(id&&order&&sameItems(id,expectedItems)&&truth(order['Stock Deducted'])===!!expectedStock)return id}throw new Error('The spreadsheet write was not confirmed. Refresh and check the order before trying again.')}
 async function submit(e){e.preventDefault();if(!state.cart.length){$('saveStatus').textContent='Add at least one fragrance.';return}const editing=state.editingId,body={action:editing?'updateOrder':'createOrder',order:payload()};if(editing)body.orderId=editing;$('saveStatus').textContent=editing?'Updating order…':'Saving order…';$('saveOrder').disabled=true;try{const result=await DeadEndAdminWrite.submit(state.settings.adminWriteEndpoint,body);const savedId=result.orderId||editing;$('saveStatus').textContent=editing?'Order updated successfully.':'Order saved successfully.';resetForm();await refreshOrderData();if(savedId)openOrder(savedId)}catch(err){$('saveStatus').textContent='Save failed: '+err.message}finally{$('saveOrder').disabled=false}}
 function orderItems(id){return state.items.filter(x=>x['Order ID']===id)}
 function renderOrders(){const q=($('orderSearch').value||'').toLowerCase(),rows=state.orders.filter(o=>Object.values(o).join(' ').toLowerCase().includes(q)).slice(0,150);$('ordersList').innerHTML=rows.map(o=>`<article class="history-card phase5-order" data-open="${esc(o['Order ID'])}"><div><strong>${esc(o['Order ID']||'Order')}</strong><small>${esc(o['Order Date']||'')} · ${esc(o.Customer||'Unknown')}</small></div><div><span>${esc(o['Order Status']||'')}</span><strong>${money(o['Total Paid'])}</strong></div></article>`).join('')||'<div class="empty">No orders found.</div>';document.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>openOrder(x.dataset.open))}
 function openOrder(id){const o=state.orders.find(x=>x['Order ID']===id),its=orderItems(id);if(!o)return;$('orderDetail').innerHTML=`<div class="shipping-detail-head"><div><p class="eyebrow">Order detail</p><h2>${esc(id)}</h2><p>${esc(o['Order Date'])} · ${esc(o.Customer)}</p></div><strong>${money(o['Total Paid'])}</strong></div><div class="phase5-detail-grid"><section><h3>Items</h3>${its.map(i=>`<div class="mini-row"><span>${esc(i.House+' · '+i.Fragrance)} · ${esc(i['Size mL'])}mL × ${esc(i.Quantity)}</span><strong>${money(i['Line Total'])}</strong></div>`).join('')||'<div class="empty">No items found.</div>'}</section><section><h3>Order</h3><p><b>Status:</b> ${esc(o['Order Status'])}</p><p><b>Payment:</b> ${esc(o['Payment Status'])}</p><p><b>Tracking:</b> ${esc(o['Tracking Number']||'—')}</p><p><b>Stock deducted:</b> ${esc(o['Stock Deducted']||'FALSE')}</p></section></div><div class="phase5-actions"><button class="button primary" id="editThisOrder">Edit order</button><button class="button" id="duplicateThisOrder">Duplicate as new</button><button class="button subtle" id="copyThisOrder">Copy summary</button></div><p id="detailStatus" class="muted"></p>`;$('editThisOrder').onclick=()=>editOrder(id);$('duplicateThisOrder').onclick=()=>duplicateOrder(id);$('copyThisOrder').onclick=()=>navigator.clipboard.writeText(`${id} — ${o.Customer} — ${money(o['Total Paid'])}\n`+its.map(i=>`${i.Fragrance} ${i['Size mL']}mL × ${i.Quantity}`).join('\n'));$('orderDialog').showModal()}
 function editOrder(id){const o=state.orders.find(x=>x['Order ID']===id),its=orderItems(id);if(!o)return;if(/historical import/i.test(o['Sales Source']||'')){alert('Historical imports are protected from item editing. Status and tracking can still be managed from Shipping.');return}state.editingId=id;state.cart=its.map(i=>({fragranceId:i['Fragrance ID'],house:i.House||'',fragrance:i.Fragrance||'',sizeMl:num(i['Size mL']),quantity:Math.max(1,num(i.Quantity)),priceEach:num(i['Price Each']),productCost:num(i['Product Cost'])}));$('orderDate').value=String(o['Order Date']||'').slice(0,10);$('customer').value=o.Customer||'';$('salesSource').value=o['Sales Source']||'Direct';$('paymentStatus').value=o['Payment Status']||'Paid';$('orderStatus').value=o['Order Status']||'New';$('trackingNumber').value=o['Tracking Number']||'';$('postage').value=num(o.Postage);$('discount').value=num(o.Discount);$('notes').value=o.Notes||'';$('deductStock').checked=truth(o['Stock Deducted']);$('formMode').textContent='Editing '+id;$('formTitle').textContent='Correct order';$('saveOrder').textContent='Update Order';$('cancelEdit').hidden=false;renderCart();$('orderDialog').close();scrollTo({top:0,behavior:'smooth'})}
 async function duplicateOrder(id){if(!confirm('Create a new pending order using the same customer and items? Stock will not be deducted until you review it.'))return;$('detailStatus').textContent='Duplicating…';try{const result=await DeadEndAdminWrite.submit(state.settings.adminWriteEndpoint,{action:'duplicateOrder',orderId:id});await refreshOrderData();$('detailStatus').textContent='Duplicate created: '+(result.orderId||'new order')+'.'}catch(err){$('detailStatus').textContent='Duplicate failed: '+err.message}}
 function normText(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/&/g,' and ').replace(/\b(eau de parfum|eau de toilette|edp|edt|parfum|extrait|perfume|perfumes|fragrance|sample|decant)\b/g,' ').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim()}
 function tokenScore(a,b){const A=new Set(normText(a).split(' ').filter(x=>x.length>1)),B=new Set(normText(b).split(' ').filter(x=>x.length>1));if(!A.size||!B.size)return 0;let hit=0;A.forEach(x=>{if(B.has(x))hit++});return (2*hit)/(A.size+B.size)}
 function matchCatalogue(raw){const q=normText(raw);if(!q)return [];const scored=state.catalogue.map(p=>{const full=[p.House,p.Fragrance].filter(Boolean).join(' '),f=normText(p.Fragrance),h=normText(p.House);let score=tokenScore(q,full);if(f&&q.includes(f))score+=.65;if(h&&q.includes(h))score+=.2;if(normText(full)===q)score+=1;return {p,score}}).filter(x=>x.score>=.46).sort((a,b)=>b.score-a.score);if(!scored.length)return [];const best=scored[0].score;return scored.filter((x,i)=>i<5&&x.score>=best-.12)}
 function parseLine(line){const clean=String(line||'').trim();if(!clean)return null;const sizeMatch=clean.match(/\b(3|5|10)\s*(?:ml|mL)\b/i);if(!sizeMatch)return null;const size=num(sizeMatch[1]);let qty=1;const before=clean.slice(0,sizeMatch.index);const q1=before.match(/(?:^|\s)(\d+)\s*[x×]\s*$/i),q2=clean.match(/\b(?:qty|quantity)\s*[:x]?\s*(\d+)\b/i),q3=clean.match(/^\s*(\d+)\s*[x×]\s*/i);if(q1)qty=Math.max(1,num(q1[1]));else if(q2)qty=Math.max(1,num(q2[1]));else if(q3)qty=Math.max(1,num(q3[1]));let query=clean.replace(/\b(3|5|10)\s*ml\b/ig,' ').replace(/^\s*\d+\s*[x×]\s*/i,' ').replace(/\b(?:qty|quantity)\s*[:x]?\s*\d+\b/ig,' ').replace(/[-–—,:;()\[\]]+/g,' ').replace(/\s+/g,' ').trim();return {raw:clean,size,qty,query,matches:matchCatalogue(query),selected:null}}
 function detectCustomer(text){const m=String(text||'').match(/(?:^|\n)\s*(?:name|customer)\s*[:\-]\s*([^\n]+)/i);return m?m[1].trim():''}
 function detectPostage(text){const t=String(text||'').toLowerCase();if(/express\s*(post|postage|shipping)|\bexpress\b/.test(t))return num(state.settings&&state.settings.expressPostage)||10;if(/pick\s*up|pickup|collect/.test(t))return 0;return null}
 function parseOrderMessage(){const text=$('orderMessage').value.trim();if(!text){$('messageParseStatus').textContent='Paste a customer message first.';return}const lines=text.split(/\n|(?<=\bml)[,;]+/i).map(parseLine).filter(Boolean);state.messageLines=lines;const customer=detectCustomer(text);if(customer)$('customer').value=customer;const post=detectPostage(text);if(post!==null)$('postage').value=post;$('salesSource').value='Facebook';renderMessagePreview()}
 function renderMessagePreview(){const rows=state.messageLines||[];if(!rows.length){$('messagePreview').innerHTML='<div class="empty">No 3mL, 5mL or 10mL order lines were detected. Try putting each fragrance on its own line.</div>';$('messageParseStatus').textContent='No order items detected.';return}let exact=0,warn=0;rows.forEach((r,i)=>{if(!r.selected&&r.matches.length===1)r.selected=String(r.matches[0].p.ID);if(r.selected)exact++;else warn++});$('messageParseStatus').textContent=`${rows.length} item line${rows.length===1?'':'s'} detected · ${exact} ready · ${warn} need review`;$('messagePreview').innerHTML=rows.map((r,i)=>{const opts=r.matches.map(m=>`<option value="${esc(m.p.ID)}" ${String(r.selected)===String(m.p.ID)?'selected':''}>${esc(productName(m.p))}</option>`).join('');const status=r.matches.length===0?'No catalogue match':r.matches.length===1?'Matched':'Choose best match';return `<article class="message-match ${r.matches.length===0?'unmatched':''}"><div class="message-original"><strong>${esc(r.raw)}</strong><small>${r.qty} × ${r.size}mL</small></div><label><span>${esc(status)}</span><select data-msg-match="${i}"><option value="">${r.matches.length?'Select fragrance…':'No match found'}</option>${opts}</select></label></article>`}).join('')+`<div class="message-review-actions"><button id="applyParsedOrder" class="button primary" type="button">Add matched items to order</button><span class="muted">Review every match before adding. Stock is not deducted yet.</span></div>`;document.querySelectorAll('[data-msg-match]').forEach(e=>e.onchange=()=>{state.messageLines[num(e.dataset.msgMatch)].selected=e.value;renderMessagePreview()});$('applyParsedOrder').onclick=applyParsedOrder}
 function applyParsedOrder(){const rows=state.messageLines||[],unresolved=rows.filter(r=>!r.selected);if(unresolved.length){$('messageParseStatus').textContent=`Review ${unresolved.length} unmatched/ambiguous item${unresolved.length===1?'':'s'} before continuing.`;return}rows.forEach(r=>{const p=state.catalogue.find(x=>String(x.ID)===String(r.selected));if(!p)return;const ex=state.cart.find(x=>String(x.fragranceId)===String(p.ID)&&x.sizeMl===r.size);if(ex)ex.quantity+=r.qty;else state.cart.push({fragranceId:p.ID,house:p.House||'',fragrance:p.Fragrance||'',sizeMl:r.size,quantity:r.qty,priceEach:price(p,r.size)})});renderCart();$('notes').value=[$('notes').value.trim(),'Imported from customer message:\n'+$('orderMessage').value.trim()].filter(Boolean).join('\n\n');$('messageParseStatus').textContent=`${rows.length} matched item line${rows.length===1?'':'s'} added. Review quantities, prices, customer and postage, then Save Order.`;$('messageImportBody').hidden=true;scrollTo({top:$('orderItems').getBoundingClientRect().top+scrollY-120,behavior:'smooth'})}
 function copyOrderSummary(){if(!state.cart.length)return '';const lines=state.cart.map(x=>`${x.quantity>1?x.quantity+' × ':''}${x.house} – ${x.fragrance} · ${x.sizeMl}mL — ${money(x.quantity*x.priceEach)}`),post=num($('postage').value),disc=num($('discount').value),total=state.cart.reduce((a,x)=>a+x.quantity*x.priceEach,0)+post-disc;return ['Perfect! Your order is:',...lines,post?`Express postage — ${money(post)}`:'',disc?`Discount — -${money(disc)}`:'',`Total: ${money(total)}`].filter(Boolean).join('\n')}
 function resetForm(){state.editingId=null;state.cart=[];state.messageLines=[];$('orderDate').value=new Date().toISOString().slice(0,10);if(state.settings)$('postage').value=state.settings.expressPostage??10;$('discount').value=0;$('customer').value='';$('notes').value='';$('trackingNumber').value='';$('deductStock').checked=true;$('formMode').textContent='Quick Sale';$('formTitle').textContent='New order';$('saveOrder').textContent='Save Order';$('cancelEdit').hidden=true;renderCart()}
 document.addEventListener('DOMContentLoaded',()=>{$('productSearch').oninput=searchProducts;$('orderForm').onsubmit=submit;$('postage').oninput=calc;$('discount').oninput=calc;$('clearCart').onclick=()=>{state.cart=[];renderCart()};$('refreshOrders').onclick=()=>Promise.all([loadOrders(),loadItems()]);$('orderSearch').oninput=renderOrders;$('cancelEdit').onclick=resetForm;$('closeOrderDialog').onclick=()=>$('orderDialog').close();$('toggleMessageImport').onclick=()=>{$('messageImportBody').hidden=!$('messageImportBody').hidden};$('parseMessage').onclick=parseOrderMessage;$('clearMessage').onclick=()=>{$('orderMessage').value='';state.messageLines=[];$('messagePreview').innerHTML='';$('messageParseStatus').textContent=''};load().catch(e=>$('saveStatus').textContent=e.message)});
})();