(function(){
 const $=id=>document.getElementById(id), state={settings:null,catalogue:[],cart:[],orders:[],items:[],editingId:null};
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const num=v=>Number(String(v??'').replace(/[^0-9.-]/g,''))||0,money=v=>'$'+num(v).toFixed(2),truth=v=>/^(true|1|yes)$/i.test(String(v||''));
 async function load(){state.settings=await fetch('../settings.json',{cache:'no-store'}).then(r=>r.json());resetForm();await Promise.all([loadCatalogue(),loadOrders(),loadItems()]);}
 async function get(action){const ep=state.settings.adminWriteEndpoint,u=ep+(ep.includes('?')?'&':'?')+'action='+encodeURIComponent(action)+'&t='+Date.now();return fetch(u,{cache:'no-store'}).then(r=>r.json())}
 async function loadCatalogue(){const d=await get('catalogue');state.catalogue=d.items||[]}
 async function loadOrders(){const d=await get('orders');state.orders=d.items||[];renderOrders()}
 async function loadItems(){const d=await get('orderItems');state.items=d.items||[]}
 function productName(i){return [i.House,i.Fragrance].filter(Boolean).join(' · ')} function price(i,s){return num(i[s+'mL'])}
 function searchProducts(){const q=$('productSearch').value.trim().toLowerCase();if(q.length<2){$('productResults').innerHTML='';return}const rows=state.catalogue.filter(i=>[i.ID,i.House,i.Fragrance].join(' ').toLowerCase().includes(q)).slice(0,12);$('productResults').innerHTML=rows.map(i=>`<article class="picker-card"><div><strong>${esc(productName(i))}</strong><small>${esc(i.Collection||'Catalogue')} · ${esc(i['Current mL']||i['Current Amount Left (mL)']||'—')}mL left</small></div><div class="size-actions">${[3,5,10].map(s=>`<button type="button" data-id="${esc(i.ID)}" data-size="${s}">${s}mL · ${money(price(i,s))}</button>`).join('')}</div></article>`).join('')||'<div class="empty">No matching fragrances.</div>';document.querySelectorAll('.size-actions button').forEach(b=>b.onclick=()=>addItem(b.dataset.id,num(b.dataset.size)))}
 function addItem(id,size){const p=state.catalogue.find(x=>String(x.ID)===String(id));if(!p)return;const ex=state.cart.find(x=>String(x.fragranceId)===String(id)&&x.sizeMl===size);if(ex)ex.quantity++;else state.cart.push({fragranceId:id,house:p.House||'',fragrance:p.Fragrance||'',sizeMl:size,quantity:1,priceEach:price(p,size)});renderCart();$('productSearch').value='';$('productResults').innerHTML=''}
 function renderCart(){if(!state.cart.length){$('orderItems').innerHTML='<div class="empty">Search and add a fragrance.</div>';calc();return}$('orderItems').innerHTML=state.cart.map((x,i)=>`<article class="order-line"><div><strong>${esc(x.house+' · '+x.fragrance)}</strong><small>${x.sizeMl}mL</small></div><label>Qty<input type="number" min="1" value="${x.quantity}" data-q="${i}"></label><label>Price<input type="number" min="0" step="0.01" value="${x.priceEach}" data-p="${i}"></label><strong>${money(x.quantity*x.priceEach)}</strong><button type="button" class="icon-button" data-r="${i}">×</button></article>`).join('');document.querySelectorAll('[data-q]').forEach(e=>e.oninput=()=>{state.cart[num(e.dataset.q)].quantity=Math.max(1,num(e.value));renderCart()});document.querySelectorAll('[data-p]').forEach(e=>e.oninput=()=>{state.cart[num(e.dataset.p)].priceEach=num(e.value);calc()});document.querySelectorAll('[data-r]').forEach(e=>e.onclick=()=>{state.cart.splice(num(e.dataset.r),1);renderCart()});calc()}
 function calc(){const subtotal=state.cart.reduce((a,x)=>a+x.quantity*x.priceEach,0);$('grandTotal').textContent=money(subtotal+num($('postage').value)-num($('discount').value))}
 function payload(){return {orderDate:$('orderDate').value,customer:$('customer').value.trim(),salesSource:$('salesSource').value,paymentStatus:$('paymentStatus').value,orderStatus:$('orderStatus').value,trackingNumber:$('trackingNumber').value.trim(),postage:num($('postage').value),discount:num($('discount').value),notes:$('notes').value.trim(),deductStock:$('deductStock').checked,items:state.cart}}
 async function verify(id,tries=8){for(let i=0;i<tries;i++){await new Promise(r=>setTimeout(r,650));await loadOrders();if(state.orders.some(o=>o['Order ID']===id))return true}return false}
 async function submit(e){e.preventDefault();if(!state.cart.length){$('saveStatus').textContent='Add at least one fragrance.';return}const editing=state.editingId, action=editing?'updateOrder':'createOrder', body={action,order:payload()};if(editing)body.orderId=editing;$('saveStatus').textContent=editing?'Updating order…':'Saving order…';try{await DeadEndAdminWrite.submit(state.settings.adminWriteEndpoint,body);await Promise.all([loadOrders(),loadItems()]);$('saveStatus').textContent=editing?'Order updated successfully.':'Order saved successfully.';resetForm()}catch(err){$('saveStatus').textContent='Could not save: '+err.message}}
 function orderItems(id){return state.items.filter(x=>x['Order ID']===id)}
 function renderOrders(){const q=($('orderSearch').value||'').toLowerCase(),rows=state.orders.filter(o=>Object.values(o).join(' ').toLowerCase().includes(q)).slice(0,150);$('ordersList').innerHTML=rows.map(o=>`<article class="history-card phase5-order" data-open="${esc(o['Order ID'])}"><div><strong>${esc(o['Order ID']||'Order')}</strong><small>${esc(o['Order Date']||'')} · ${esc(o.Customer||'Unknown')}</small></div><div><span>${esc(o['Order Status']||'')}</span><strong>${money(o['Total Paid'])}</strong></div></article>`).join('')||'<div class="empty">No orders found.</div>';document.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>openOrder(x.dataset.open))}
 function openOrder(id){const o=state.orders.find(x=>x['Order ID']===id),its=orderItems(id);if(!o)return;$('orderDetail').innerHTML=`<div class="shipping-detail-head"><div><p class="eyebrow">Order detail</p><h2>${esc(id)}</h2><p>${esc(o['Order Date'])} · ${esc(o.Customer)}</p></div><strong>${money(o['Total Paid'])}</strong></div><div class="phase5-detail-grid"><section><h3>Items</h3>${its.map(i=>`<div class="mini-row"><span>${esc(i.House+' · '+i.Fragrance)} · ${esc(i['Size mL'])}mL × ${esc(i.Quantity)}</span><strong>${money(i['Line Total'])}</strong></div>`).join('')||'<div class="empty">No items found.</div>'}</section><section><h3>Order</h3><p><b>Status:</b> ${esc(o['Order Status'])}</p><p><b>Payment:</b> ${esc(o['Payment Status'])}</p><p><b>Tracking:</b> ${esc(o['Tracking Number']||'—')}</p><p><b>Stock deducted:</b> ${esc(o['Stock Deducted']||'FALSE')}</p></section></div><div class="phase5-actions"><button class="button primary" id="editThisOrder">Edit order</button><button class="button" id="duplicateThisOrder">Duplicate as new</button><button class="button subtle" id="copyThisOrder">Copy summary</button></div><p id="detailStatus" class="muted"></p>`;$('editThisOrder').onclick=()=>editOrder(id);$('duplicateThisOrder').onclick=()=>duplicateOrder(id);$('copyThisOrder').onclick=()=>navigator.clipboard.writeText(`${id} — ${o.Customer} — ${money(o['Total Paid'])}\n`+its.map(i=>`${i.Fragrance} ${i['Size mL']}mL × ${i.Quantity}`).join('\n'));$('orderDialog').showModal()}
 function editOrder(id){const o=state.orders.find(x=>x['Order ID']===id),its=orderItems(id);if(!o)return;if(/historical import/i.test(o['Sales Source']||'')){alert('Historical imports are protected from item editing. Status and tracking can still be managed from Shipping.');return}state.editingId=id;state.cart=its.map(i=>({fragranceId:i['Fragrance ID'],house:i.House||'',fragrance:i.Fragrance||'',sizeMl:num(i['Size mL']),quantity:Math.max(1,num(i.Quantity)),priceEach:num(i['Price Each']),productCost:num(i['Product Cost'])}));$('orderDate').value=String(o['Order Date']||'').slice(0,10);$('customer').value=o.Customer||'';$('salesSource').value=o['Sales Source']||'Direct';$('paymentStatus').value=o['Payment Status']||'Paid';$('orderStatus').value=o['Order Status']||'New';$('trackingNumber').value=o['Tracking Number']||'';$('postage').value=num(o.Postage);$('discount').value=num(o.Discount);$('notes').value=o.Notes||'';$('deductStock').checked=truth(o['Stock Deducted']);$('formMode').textContent='Editing '+id;$('formTitle').textContent='Correct order';$('saveOrder').textContent='Update Order';$('cancelEdit').hidden=false;renderCart();$('orderDialog').close();scrollTo({top:0,behavior:'smooth'})}
 async function duplicateOrder(id){if(!confirm('Create a new pending order using the same customer and items? Stock will not be deducted until you review it.'))return;$('detailStatus').textContent='Duplicating…';await DeadEndAdminWrite.submit(state.settings.adminWriteEndpoint,{action:'duplicateOrder',orderId:id});setTimeout(async()=>{await Promise.all([loadOrders(),loadItems()]);$('detailStatus').textContent='Duplicate created as a new pending order.'},1800)}
 function resetForm(){state.editingId=null;state.cart=[];$('orderDate').value=new Date().toISOString().slice(0,10);if(state.settings)$('postage').value=state.settings.expressPostage??10;$('discount').value=0;$('customer').value='';$('notes').value='';$('trackingNumber').value='';$('deductStock').checked=true;$('formMode').textContent='Quick Sale';$('formTitle').textContent='New order';$('saveOrder').textContent='Save Order';$('cancelEdit').hidden=true;renderCart()}
 document.addEventListener('DOMContentLoaded',()=>{$('productSearch').oninput=searchProducts;$('orderForm').onsubmit=submit;$('postage').oninput=calc;$('discount').oninput=calc;$('clearCart').onclick=()=>{state.cart=[];renderCart()};$('refreshOrders').onclick=()=>Promise.all([loadOrders(),loadItems()]);$('orderSearch').oninput=renderOrders;$('cancelEdit').onclick=resetForm;$('closeOrderDialog').onclick=()=>$('orderDialog').close();load().catch(e=>$('saveStatus').textContent=e.message)});
})();