(function(){
 const $=id=>document.getElementById(id), state={settings:null,catalogue:[],cart:[],orders:[]};
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const num=v=>Number(String(v??'').replace(/[^0-9.-]/g,''))||0, money=v=>'$'+num(v).toFixed(2);
 function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===','&&!q){row.push(cell);cell='';continue}if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(v=>String(v).trim()))rows.push(row);row=[];continue}cell+=c}row.push(cell);if(row.some(v=>String(v).trim()))rows.push(row);const h=rows.shift()||[];return rows.map(r=>Object.fromEntries(h.map((x,i)=>[x.trim(),(r[i]||'').trim()]))) }
 async function load(){state.settings=await fetch('../settings.json',{cache:'no-store'}).then(r=>r.json());$('orderDate').value=new Date().toISOString().slice(0,10);$('postage').value=state.settings.expressPostage??10;await Promise.all([loadCatalogue(),loadOrders()]);}
 async function get(action){const ep=state.settings.adminWriteEndpoint,u=ep+(ep.includes('?')?'&':'?')+'action='+encodeURIComponent(action)+'&t='+Date.now();return fetch(u,{cache:'no-store'}).then(r=>r.json())}
 async function loadCatalogue(){let data=await get('catalogue').catch(()=>({}));if(data.ok&&Array.isArray(data.items))state.catalogue=data.items;else{const r=await fetch(state.settings.catalogueCsvUrl,{cache:'no-store'});state.catalogue=parseCSV(await r.text())}}
 async function loadOrders(){const data=await get('orders').catch(()=>({items:[]}));state.orders=data.items||[];renderOrders()}
 function price(item,size){return num(item[size+'mL'])}
 function productName(i){return [i.House,i.Fragrance].filter(Boolean).join(' · ')}
 function searchProducts(){const q=$('productSearch').value.trim().toLowerCase();if(q.length<2){$('productResults').innerHTML='';return}const rows=state.catalogue.filter(i=>[i.ID,i.House,i.Fragrance].join(' ').toLowerCase().includes(q)).slice(0,12);$('productResults').innerHTML=rows.map(i=>`<article class="picker-card"><div><strong>${esc(productName(i))}</strong><small>${esc(i.Collection||'Catalogue')} · ${esc(i['Current mL']||i['Current Amount Left (mL)']||'—')}mL left</small></div><div class="size-actions">${[3,5,10].map(s=>`<button type="button" data-id="${esc(i.ID)}" data-size="${s}">${s}mL · ${money(price(i,s))}</button>`).join('')}</div></article>`).join('')||'<div class="empty">No matching fragrances.</div>';document.querySelectorAll('.size-actions button').forEach(b=>b.onclick=()=>addItem(b.dataset.id,num(b.dataset.size)))}
 function addItem(id,size){const p=state.catalogue.find(x=>String(x.ID)===String(id));if(!p)return;const existing=state.cart.find(x=>x.fragranceId===id&&x.sizeMl===size);if(existing)existing.quantity++;else state.cart.push({fragranceId:id,house:p.House||'',fragrance:p.Fragrance||'',sizeMl:size,quantity:1,priceEach:price(p,size)});renderCart();$('productSearch').value='';$('productResults').innerHTML=''}
 function renderCart(){if(!state.cart.length){$('orderItems').innerHTML='<div class="empty">Search and add a fragrance.</div>';calc();return}$('orderItems').innerHTML=state.cart.map((x,i)=>`<article class="order-line"><div><strong>${esc(x.house+' · '+x.fragrance)}</strong><small>${x.sizeMl}mL</small></div><label>Qty<input type="number" min="1" value="${x.quantity}" data-q="${i}"></label><label>Price<input type="number" min="0" step="0.01" value="${x.priceEach}" data-p="${i}"></label><strong>${money(x.quantity*x.priceEach)}</strong><button type="button" class="icon-button" data-r="${i}" aria-label="Remove">×</button></article>`).join('');document.querySelectorAll('[data-q]').forEach(e=>e.oninput=()=>{state.cart[num(e.dataset.q)].quantity=Math.max(1,num(e.value));renderCart()});document.querySelectorAll('[data-p]').forEach(e=>e.oninput=()=>{state.cart[num(e.dataset.p)].priceEach=num(e.value);calc()});document.querySelectorAll('[data-r]').forEach(e=>e.onclick=()=>{state.cart.splice(num(e.dataset.r),1);renderCart()});calc()}
 function calc(){const subtotal=state.cart.reduce((a,x)=>a+x.quantity*x.priceEach,0);$('grandTotal').textContent=money(subtotal+num($('postage').value)-num($('discount').value))}
 async function submit(e){e.preventDefault();if(!state.cart.length){$('saveStatus').textContent='Add at least one fragrance.';return}const payload={action:'createOrder',order:{orderDate:$('orderDate').value,customer:$('customer').value.trim(),salesSource:$('salesSource').value,paymentStatus:$('paymentStatus').value,orderStatus:$('orderStatus').value,postage:num($('postage').value),discount:num($('discount').value),notes:$('notes').value.trim(),deductStock:$('deductStock').checked,items:state.cart}};$('saveStatus').textContent='Saving order…';try{await DeadEndAdminWrite.submit(state.settings.adminWriteEndpoint,payload);$('saveStatus').textContent='Order submitted. Refreshing history…';state.cart=[];renderCart();$('customer').value='';setTimeout(loadOrders,2500)}catch(err){$('saveStatus').textContent='Could not save: '+err.message}}
 function renderOrders(){const q=($('orderSearch')?.value||'').toLowerCase();const rows=state.orders.filter(o=>Object.values(o).join(' ').toLowerCase().includes(q)).slice(0,100);$('ordersList').innerHTML=rows.map(o=>`<article class="history-card"><div><strong>${esc(o['Order ID']||'Order')}</strong><small>${esc(o['Order Date']||'')} · ${esc(o.Customer||'Unknown')}</small></div><div><span>${esc(o['Order Status']||'')}</span><strong>${money(o['Total Paid'])}</strong></div></article>`).join('')||'<div class="empty">No orders found.</div>'}
 async function setup(){ $('setupStatus').textContent='Creating/checking sheets…';await DeadEndAdminWrite.submit(state.settings.adminWriteEndpoint,{action:'setupOrderSheets'});$('setupStatus').textContent='Setup request submitted. Sheets should now be ready.' }
 document.addEventListener('DOMContentLoaded',()=>{$('productSearch').oninput=searchProducts;$('orderForm').onsubmit=submit;$('postage').oninput=calc;$('discount').oninput=calc;$('clearCart').onclick=()=>{state.cart=[];renderCart()};$('refreshOrders').onclick=loadOrders;$('orderSearch').oninput=renderOrders;$('setupSheets').onclick=setup;load().catch(e=>{$('saveStatus').textContent=e.message})});
})();
