(function(){
  const $=(id)=>document.getElementById(id);
  const state={settings:null,items:[],selected:null,selectedIds:new Set(),visible:[]};
  const esc=(v)=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const num=(v)=>Number(String(v??'').replace(/[^0-9.\-]/g,''))||0;
  const slugify=(v)=>String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,92);
  function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;continue;}if(c==='"'){q=!q;continue;}if(c===','&&!q){row.push(cell);cell='';continue;}if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(v=>String(v).trim()!==''))rows.push(row);row=[];continue;}cell+=c;}row.push(cell);if(row.some(v=>String(v).trim()!==''))rows.push(row);if(!rows.length)return[];const h=rows.shift().map(x=>x.trim());return rows.map(r=>Object.fromEntries(h.map((x,i)=>[x,(r[i]||'').trim()])));} 
  function name(i){return [i.House,i.Fragrance].filter(Boolean).join(' · ') || i.ID || 'Untitled';}
  function pageName(i){return [i.House,i.Fragrance].filter(Boolean).join(' ') || i.Fragrance || 'Fragrance';}
  function stock(i){return i.Stock || i.Status || 'Unknown';}
  function score(i){return num(i['SEO Score']) || calculateScore(i);}
  function scoreClass(sc){if(sc>=90)return'excellent';if(sc>=70)return'good';if(sc>=50)return'ok';return'poor';}
  function calculateScore(i){let s=0;if(i.Image)s+=15;if(String(i.Description||'').length>=50)s+=10;if(i.Performance)s+=10;if(i.Projection)s+=10;if(i.Season)s+=10;if(i.Occasion)s+=10;if(i['SEO Slug'])s+=10;if(i['SEO Title'])s+=10;if(i['SEO Description'])s+=15;if(i['SEO FAQ'])s+=10;if(i['SEO Internal Links'])s+=5;if(hasSchemaReady(i))s+=5;return Math.min(100,s);}
  function hasSchemaReady(i){return !!(i.Image && (i['3mL']||i['5mL']||i['10mL']) && (i['SEO Slug']||i.Fragrance) && (i['SEO Title']||i.Description));}
  function missingChecks(i){return [
    ['Image',!!i.Image,15],['Description',String(i.Description||'').length>=50,10],['Performance',!!i.Performance,10],['Projection',!!i.Projection,10],['Season',!!i.Season,10],['Occasion',!!i.Occasion,10],['Slug',!!i['SEO Slug'],10],['Meta title',!!i['SEO Title'],10],['Meta description',!!i['SEO Description'],15],['FAQ',!!i['SEO FAQ'],10],['Internal links',!!i['SEO Internal Links'],5],['Schema ready',hasSchemaReady(i),5]
  ];}
  async function loadSettings(){state.settings=await fetch('../settings.json',{cache:'no-store'}).then(r=>r.json());try{const ep=state.settings.adminWriteEndpoint;const live=await fetch(ep+(ep.includes('?')?'&':'?')+'action=settings&t='+Date.now(),{cache:'no-store'}).then(r=>r.json());state.settings=Object.assign({},state.settings,live.settings||{});}catch(e){console.warn('Live settings unavailable',e);}}
  async function loadCatalogue(){let items=[];try{const ep=state.settings.adminWriteEndpoint;const live=await fetch(ep+(ep.includes('?')?'&':'?')+'action=catalogue&t='+Date.now(),{cache:'no-store'}).then(r=>r.json());if(live.ok&&Array.isArray(live.items))items=live.items;}catch(e){console.warn('Live catalogue unavailable, using CSV',e);}if(!items.length){try{const res=await fetch(state.settings.catalogueCsvUrl,{cache:'no-store'});if(res.ok)items=parseCSV(await res.text());}catch(e){}}state.items=items;renderStats();renderFilters();renderList();}
  function renderStats(){const items=state.items.filter(i=>!['hidden','archived'].includes(stock(i).toLowerCase()));const avg=items.length?Math.round(items.reduce((a,i)=>a+score(i),0)/items.length):0;$('statTotal').textContent=items.length;$('statAverage').textContent=avg?avg+'%':'—';$('statImage').textContent=items.filter(i=>!i.Image).length;$('statMissing').textContent=items.filter(i=>!i['SEO Title']||!i['SEO Description']||!i['SEO FAQ']).length;}
  function renderFilters(){const vals=[...new Set(state.items.map(i=>i.Collection).filter(Boolean))].sort();$('collectionFilter').innerHTML='<option value="">All</option>'+vals.map(v=>`<option>${esc(v)}</option>`).join('');}
  function filtered(){const q=$('search').value.toLowerCase().trim();const col=$('collectionFilter').value;const h=$('healthFilter').value;return state.items.filter(i=>{const hay=[i.ID,i.House,i.Fragrance,i.Collection,i['Scent Style']].join(' ').toLowerCase();const sc=score(i);return (!q||hay.includes(q))&&(!col||i.Collection===col)&&(!h||(h==='poor'&&sc<70)||(h==='good'&&sc>=70)||(h==='excellent'&&sc>=90)||(h==='missing'&&!i['SEO Title']));}).slice(0,250);}
  function renderList(){const rows=filtered();state.visible=rows;$('visibleCount').textContent=rows.length+' visible';$('seoList').innerHTML=rows.map(i=>{const sc=score(i);const cls=scoreClass(sc);const checked=state.selectedIds.has(String(i.ID))?'checked':'';const issues=missingChecks(i).filter(([,ok])=>!ok).slice(0,3).map(([label])=>`<b>${esc(label)}</b>`).join('');return `<article class="inventory-card-v52 seo-row ${state.selected&&String(state.selected.ID)===String(i.ID)?'active':''}" data-id="${esc(i.ID)}"><label class="seo-select" title="Select for bulk actions"><input type="checkbox" data-select-id="${esc(i.ID)}" ${checked}></label><button class="seo-row-button" type="button" data-id="${esc(i.ID)}"><span class="thumb">${i.Image?`<img src="${esc(i.Image)}" alt="">`:'🧴'}</span><span class="inv-main"><strong>${esc(name(i))}</strong><em>${esc(i.Collection||'Catalogue')} · ${esc(stock(i))}</em><small><b class="score-chip ${cls}">${sc}/100</b>${issues}</small></span><span class="inv-metric"><strong>${esc(i['SEO Slug']||slugify(`${i.House||''} ${i.Fragrance||''} sample australia`)||'No slug')}</strong><em>${esc(i.Season||'')}</em></span></button></article>`;}).join('')||'<div class="empty">No bottles found.</div>';document.querySelectorAll('.seo-row-button').forEach(b=>b.addEventListener('click',()=>selectItem(b.dataset.id)));document.querySelectorAll('[data-select-id]').forEach(c=>c.addEventListener('change',()=>{if(c.checked)state.selectedIds.add(String(c.dataset.selectId));else state.selectedIds.delete(String(c.dataset.selectId));$('selectVisible').checked=rows.length&&rows.every(i=>state.selectedIds.has(String(i.ID)));}));}
  function generatedFields(i){const p=pageName(i);const slug=i['SEO Slug']||slugify(`${i.House||''} ${i.Fragrance||''} sample australia`);const title=i['SEO Title']||`${p} Sample Australia | DeadEnd Scents`;const desc=i['SEO Description']||trim(`Buy ${p} samples and decants in Australia. Available in 3mL, 5mL and 10mL from DeadEnd Scents. ${[i['Scent Style'],i.Season,i.Occasion].filter(Boolean).join(' · ')}`,158);const similar=i['SEO Similar Fragrances']||state.items.filter(x=>x.ID!==i.ID&&(x['Scent Style']===i['Scent Style']||x.Collection===i.Collection)).slice(0,6).map(pageName).join(' | ');return {slug,title,desc,keywords:i['SEO Keywords']||[p,`${i.Fragrance} sample`,`${i.Fragrance} decant`,`${i.House} samples Australia`,i.Collection,i['Scent Style']].filter(Boolean).join(', '),intro:i['SEO Intro']||i.Description||`Try ${p} as a sample before buying a full bottle. Available from DeadEnd Scents in Australia.`,faq:i['SEO FAQ']||`Is ${p} available as a sample in Australia?||Yes. DeadEnd Scents offers fragrance samples and decants in Australia, subject to current stock.\nWhat does ${p} smell like?||${[i['Scent Style'],i.Description].filter(Boolean).join('. ')||'Use the scent profile and description as a guide.'}\nWhen should I wear ${p}?||${[i.Season?`Best suited to ${i.Season}`:'',i.Occasion?`Works well for ${i.Occasion}`:'',i.Performance?`Performance: ${i.Performance}`:'',i.Projection?`Projection: ${i.Projection}`:''].filter(Boolean).join('. ')||'Use the season and occasion notes as a guide.'}`,similar,links:i['SEO Internal Links']||[`/fragrances/${slug}/`,i.House?`/houses/${slugify(i.House)}/`:'',i.Collection?`/#catalogue`:''].filter(Boolean).join(' | ')};}
  function trim(text,max){text=String(text||'').replace(/\s+/g,' ').trim();return text.length<=max?text:text.slice(0,max-1).replace(/\s+\S*$/,'')+'…';}
  function fillForm(i){const g=generatedFields(i);$('editId').value=i.ID||'';$('seoSlug').value=g.slug;$('seoTitle').value=g.title;$('seoDescription').value=g.desc;$('seoKeywords').value=g.keywords;$('seoIntro').value=g.intro;$('seoFaq').value=g.faq;$('seoSimilar').value=g.similar;$('seoLinks').value=g.links;updatePreview();}
  function selectItem(id){const i=state.items.find(x=>String(x.ID)===String(id));if(!i)return;state.selected=i;$('editorPanel').hidden=false;$('editTitle').textContent=name(i);$('editMeta').textContent=[i.ID,i.Collection,i['Scent Style']].filter(Boolean).join(' · ');fillForm(i);renderList();if(window.innerWidth<900)$('editorPanel').scrollIntoView({behavior:'smooth',block:'start'});}
  function updatePreview(){const slug=$('seoSlug').value||'fragrance-slug';$('googleTitle').textContent=$('seoTitle').value||'—';$('googleUrl').textContent='deadendscents.com/fragrances/'+slug+'/';$('googleDescription').textContent=$('seoDescription').value||'—';$('targetKeywords').textContent=$('seoKeywords').value||'—';$('previewPublicPage').href='../fragrances/'+slug+'/';const fake=Object.assign({},state.selected||{}, {'SEO Slug':$('seoSlug').value,'SEO Title':$('seoTitle').value,'SEO Description':$('seoDescription').value,'SEO FAQ':$('seoFaq').value,'SEO Internal Links':$('seoLinks').value});const sc=calculateScore(fake);$('seoScore').textContent=sc+'/100';$('seoScoreBadge').className='seo-score-badge '+scoreClass(sc);$('healthCheck').innerHTML=missingChecks(fake).map(([label,ok,pts])=>`<div class="${ok?'ok':'bad'}"><strong>${ok?'✓':'•'} ${esc(label)}</strong><span>${ok?'Done':'Missing or thin'} · ${pts} pts</span></div>`).join('');}
  async function setupSeo(){const ep=state.settings.adminWriteEndpoint;$('setupStatus').textContent='Setting up SEO columns...';try{const res=await DeadEndAdminWrite.submit(ep,{action:'setupSEOColumns'});$('setupStatus').textContent=(res.message||'SEO columns checked.')+' Refresh after Google Sheets updates.';}catch(e){$('setupStatus').textContent='Setup failed: '+(e.message||e);}}
  async function generateOne(id){const res=await DeadEndAdminWrite.submit(state.settings.adminWriteEndpoint,{action:'generateFragranceSEO',id});const item=state.items.find(x=>String(x.ID)===String(id));if(item&&res.seo)Object.assign(item,res.seo);return res;}
  async function generateSeo(){if(!state.selected)return;$('saveStatus').textContent='Generating SEO...';try{await generateOne(state.selected.ID);fillForm(state.selected);renderStats();renderList();$('saveStatus').textContent='Generated and saved to Google Sheets.';}catch(e){$('saveStatus').textContent='Generate failed: '+(e.message||e);}}
  async function generateBulk(ids,label){ids=[...new Set(ids.map(String).filter(Boolean))];if(!ids.length){$('saveStatus').textContent='Nothing selected.';return;}const ok=confirm(`Generate SEO for ${ids.length} ${label || 'bottle(s)'}? This will update Google Sheets.`);if(!ok)return;$('saveStatus').textContent=`Generating SEO for ${ids.length} bottle(s)...`;let done=0,fail=0;for(const id of ids){try{await generateOne(id);done++;}catch(e){console.warn('SEO generation failed for '+id,e);fail++;}}renderStats();renderList();if(state.selected)fillForm(state.selected);$('saveStatus').textContent=`Generated ${done} bottle(s).${fail?` ${fail} failed.`:''}`;}
  async function saveSeo(e){e.preventDefault();if(!state.selected)return;const fields={'SEO Slug':$('seoSlug').value.trim(),'SEO Title':$('seoTitle').value.trim(),'SEO Description':$('seoDescription').value.trim(),'SEO Keywords':$('seoKeywords').value.trim(),'SEO Intro':$('seoIntro').value.trim(),'SEO FAQ':$('seoFaq').value.trim(),'SEO Similar Fragrances':$('seoSimilar').value.trim(),'SEO Internal Links':$('seoLinks').value.trim(),'SEO Score':$('seoScore').textContent.replace('/100','')};$('saveStatus').textContent='Saving SEO fields...';try{await DeadEndAdminWrite.submit(state.settings.adminWriteEndpoint,{action:'saveFragranceSEO',id:state.selected.ID,fields});Object.assign(state.selected,fields);renderStats();renderList();$('saveStatus').textContent='Saved SEO fields to Google Sheets.';}catch(err){$('saveStatus').textContent='Save failed: '+(err.message||err);}}
  ['search','collectionFilter','healthFilter'].forEach(id=>$(id).addEventListener('input',renderList));['seoSlug','seoTitle','seoDescription','seoKeywords','seoIntro','seoFaq','seoSimilar','seoLinks'].forEach(id=>$(id).addEventListener('input',updatePreview));$('setupSeo').addEventListener('click',setupSeo);$('refreshSeoData').addEventListener('click',loadCatalogue);$('generateSeo').addEventListener('click',generateSeo);$('seoForm').addEventListener('submit',saveSeo);$('generateSelectedSeo').addEventListener('click',()=>generateBulk([...state.selectedIds],'selected bottle(s)'));$('generateAllVisibleSeo').addEventListener('click',()=>generateBulk(state.visible.map(i=>i.ID),'visible bottle(s)'));$('generateMissingSeo').addEventListener('click',()=>generateBulk(state.items.filter(i=>!i['SEO Title']||!i['SEO Description']||!i['SEO FAQ']).map(i=>i.ID),'missing SEO bottle(s)'));$('selectVisible').addEventListener('change',e=>{state.visible.forEach(i=>{if(e.target.checked)state.selectedIds.add(String(i.ID));else state.selectedIds.delete(String(i.ID));});renderList();});loadSettings().then(loadCatalogue).catch(e=>{$('seoList').innerHTML='<div class="empty">Could not load SEO Engine: '+esc(e.message||e)+'</div>';});
})();
