(function(){
const $=id=>document.getElementById(id), state={settings:null,items:[],changes:new Map(),photoId:null,history:[]};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>{const n=Number(String(v??'').replace(/[^0-9.\-]/g,''));return Number.isFinite(n)?n:0};
const first=(o,names)=>{for(const n of names)if(o[n]!==undefined&&String(o[n]).trim()!=='')return o[n];return ''};
const current=i=>num(first(i,['Current mL','Current Amount Left (mL)','Amount Left','Remaining mL']));
const size=i=>num(first(i,['Bottle Size (mL)','Bottle Size','Size mL']))||current(i);
const name=i=>[i.House,i.Fragrance].filter(Boolean).join(' · ')||i.ID;
const dateText=v=>{if(!v)return 'Never';const d=new Date(v);return Number.isNaN(d)?String(v):d.toLocaleDateString('en-AU')};
function setOptions(id,vals,label){const el=$(id),cur=el.value;const clean=[...new Set(vals.filter(Boolean).map(String))].sort((a,b)=>a.localeCompare(b));el.innerHTML=`<option value="">${label}</option>`+clean.map(v=>`<option>${esc(v)}</option>`).join('');el.value=clean.includes(cur)?cur:''}
async function get(action){const ep=state.settings.adminWriteEndpoint;return fetch(ep+(ep.includes('?')?'&':'?')+'action='+action+'&t='+Date.now(),{cache:'no-store'}).then(r=>r.json())}
async function load(){state.settings=await fetch('../settings.json',{cache:'no-store'}).then(r=>r.json());try{const live=await get('settings');state.settings=Object.assign({},state.settings,live.settings||{})}catch(e){};const cat=await get('catalogue');state.items=cat.items||[];try{const h=await get('stockAdjustments');state.history=h.items||[]}catch(e){state.history=[]}setOptions('collection',state.items.map(i=>i.Collection),'All collections');setOptions('style',[...state.items.map(i=>i['Scent Style']),'Vanilla'],'All scent styles');render();renderHistory()}
function isOverdue(i){const raw=i['Last Stocktake'];if(!raw)return true;const d=new Date(raw);return Number.isNaN(d)||Date.now()-d.getTime()>90*86400000}
function confidence(i){return String(i['Stock Confidence']||'Imported')}
function filtered(){const q=$('search').value.trim().toLowerCase(),col=$('collection').value,sty=$('style').value,view=$('view').value;return state.items.filter(i=>{const hit=!q||[i.ID,i.House,i.Fragrance].join(' ').toLowerCase().includes(q);const ch=state.changes.has(String(i.ID));return hit&&(!col||i.Collection===col)&&(!sty||i['Scent Style']===sty)&&(view==='all'||view==='needs'&&isOverdue(i)||view==='changed'&&ch||view==='low'&&current(i)<=15)});}
function render(){const rows=filtered();$('statBottles').textContent=state.items.length;$('statChanged').textContent=state.changes.size;$('statOverdue').textContent=state.items.filter(isOverdue).length;$('statLowConfidence').textContent=state.items.filter(i=>/estimated|imported/i.test(confidence(i))).length;$('stocktakeList').innerHTML=rows.map(i=>{const id=String(i.ID),change=state.changes.get(id),ml=change?change.ml:current(i),delta=ml-current(i),conf=change?change.confidence:confidence(i);return `<article class="stocktake-row ${change?'is-changed':''}" data-row="${esc(id)}"><div class="stocktake-bottle">${i.Image?`<img src="${esc(i.Image)}" alt="">`:''}<div><strong>${esc(name(i))}</strong><span>${esc(id)} · ${esc(i.Collection||'Catalogue')} · ${esc(i['Scent Style']||'Unspecified')}</span><small>Last stocktake: ${esc(dateText(i['Last Stocktake']))}</small></div></div><div class="stocktake-old"><span>Recorded</span><strong>${current(i)}mL</strong><small>of ${size(i)}mL</small></div><label><span>New mL</span><input class="new-ml" data-id="${esc(id)}" type="number" min="0" max="${size(i)}" step="1" value="${ml}"></label><label><span>Confidence</span><select class="confidence" data-id="${esc(id)}">${['Manual','Photo Estimate','Estimated','Imported'].map(v=>`<option ${v===conf?'selected':''}>${v}</option>`).join('')}</select></label><div class="stocktake-actions"><button class="button photo" data-photo="${esc(id)}" type="button">Photo estimate</button><button class="button reset" data-reset="${esc(id)}" type="button" ${change?'':'disabled'}>Reset</button><small class="delta ${delta<0?'down':delta>0?'up':''}">${change?(delta>0?'+':'')+delta+'mL':'No change'}</small></div></article>`}).join('')||'<div class="empty">No bottles match these filters.</div>'}
function capture(id,ml,conf){const item=state.items.find(i=>String(i.ID)===String(id));if(!item)return;ml=Math.max(0,Math.min(size(item),num(ml)));if(ml===current(item)&&conf===confidence(item))state.changes.delete(String(id));else state.changes.set(String(id),{id:String(id),ml,confidence:conf,reason:'Physical stocktake'});render()}
async function saveAll(){if(!state.changes.size){$('saveStatus').textContent='No stock changes to save.';return}$('saveAll').disabled=true;$('saveStatus').textContent='Saving '+state.changes.size+' stock updates…';try{await DeadEndAdminWrite.submit(state.settings.adminWriteEndpoint,{action:'bulkStocktake',entries:[...state.changes.values()]},{timeout:90000});state.changes.clear();$('saveStatus').textContent='Stocktake saved successfully. Inventory history has been updated.';await load()}catch(e){$('saveStatus').textContent='Save failed: '+(e.message||e)}finally{$('saveAll').disabled=false}}
async function setup(){ $('setupStatus').textContent='Checking Catalogue fields and adjustment sheet…';try{await DeadEndAdminWrite.submit(state.settings.adminWriteEndpoint,{action:'setupOperationsColumns'});$('setupStatus').textContent='Operations fields are ready.';await load()}catch(e){$('setupStatus').textContent='Setup failed: '+(e.message||e)}}
function openPhoto(id){const i=state.items.find(x=>String(x.ID)===String(id));state.photoId=id;$('photoTitle').textContent=name(i);$('fillRange').value=Math.round((current(i)/(size(i)||1))*100);updatePhoto();$('photoDialog').showModal()}
function updatePhoto(){const i=state.items.find(x=>String(x.ID)===String(state.photoId)),pct=num($('fillRange').value);$('fillLabel').textContent=pct+'%';$('photoMl').textContent=Math.round(size(i)*pct/100)+'mL'}
function renderHistory(){$('history').innerHTML=state.history.slice(0,30).map(x=>`<div class="mini-row"><div><strong>${esc([x.House,x.Fragrance].filter(Boolean).join(' · ')||x['Bottle ID'])}</strong><span>${esc(dateText(x.Timestamp))} · ${esc(x.Reason||'Stock adjustment')} · ${esc(x.Confidence||'')}</span></div><em class="pill">${esc(x['Previous mL'])} → ${esc(x['New mL'])}mL</em></div>`).join('')||'<div class="empty">No inventory adjustments recorded yet.</div>'}
$('stocktakeList').addEventListener('change',e=>{const id=e.target.dataset.id;if(!id)return;const row=e.target.closest('.stocktake-row'),ml=row.querySelector('.new-ml').value,conf=row.querySelector('.confidence').value;capture(id,ml,conf)});
$('stocktakeList').addEventListener('click',e=>{if(e.target.dataset.photo)openPhoto(e.target.dataset.photo);if(e.target.dataset.reset){state.changes.delete(String(e.target.dataset.reset));render()}});
['search','collection','style','view'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',render));$('refresh').onclick=load;$('saveAll').onclick=saveAll;$('setupOperations').onclick=setup;$('fillRange').oninput=updatePhoto;$('photoFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const url=URL.createObjectURL(f);$('photoPreview').innerHTML=`<img src="${url}" alt="Bottle stocktake photo">`};$('applyPhoto').onclick=()=>{const i=state.items.find(x=>String(x.ID)===String(state.photoId)),ml=Math.round(size(i)*num($('fillRange').value)/100);capture(state.photoId,ml,'Photo Estimate');$('photoDialog').close()};
load().catch(e=>$('stocktakeList').innerHTML='<div class="empty">Could not load stocktake: '+esc(e.message||e)+'</div>');
})();